/**
 * Napisy ekranu: artist. Polski jest źródłem prawdy — z niego bierzemy typ.
 *
 * `timeline` to etykiety dla `LineupTimeline`/`CareerTimeline` — komponent nie
 * woła i18n() sam (rysuje SVG i chętnie idzie w wiele wierszy), więc strona
 * artysty podaje mu je propsami, w jednym obiekcie.
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  sectionFailed: "Sekcja „{name}” się nie wczytała. Reszta strony działa — to tylko ten kawałek.",
  concertsHeading: "Koncerty",
  concertsLoading: "Sprawdzam, czy i gdzie grają…",
  concertsNone: "Ani MusicBrainz, ani Ticketmaster nie ma teraz zapowiedzi tego artysty. Brak wpisu nie znaczy, że nie grają — małe kluby często nigdzie nie trafiają.",
  concertsNote: "Z zapowiedzi w MusicBrainz i Ticketmasterze.",
  concertsMine: "Koncerty w moich miastach →",
  topFromPortal: "Najwyżej oceniana w portalu",
  topFromMb: "Najwyżej oceniana w MusicBrainz",
  topBadge: "↑ ta z góry",
  wikiDiscoHeading: "Dorobek według Wikipedii",
  wikiDiscoNote: "MusicBrainz wiąże kredyty producenckie i sesyjne z pojedynczymi nagraniami, a po samej osobie ich nie odda — dla producenta i muzyka sesyjnego wychodzi pustka. To jest lista spisana ręcznie na Wikipedii. Portal jej nie sprawdził: kliknięcie szuka płyty dopiero w tym momencie.",
  wikiDiscoSource: "Źródło: Wikipedia",
  producedHeading: "Wyprodukował, zrealizował, zmasterował",
  producedNote: "Płyty, przy których pracował przy pulpicie, a nie z instrumentem. Z relacji przy wydaniach w MusicBrainz — tam, gdzie zwykle wiszą kredyty producenckie.",
  spotifyOwnNote: "Ze Spotify — tych wydawnictw MusicBrainz nie ma. Katalog Spotify jest pełniejszy, ale nie wie nic o składach ani produkcji.",
  spotifyGuestNote: "Ze Spotify — płyty innych, na których się pojawia, a których MusicBrainz nie zna.",
  fromSpotifyNote: "z katalogu Spotify, dopasowane po nazwie artysty",
  producedMore: "Pokazujemy najnowsze z {n}.",
  producedTracks: "{n} nagrań",
  fetchMore: "Pobierz następne",
  fetchMoreNote: "MusicBrainz oddaje po sto pozycji naraz — doczytanie chwilę trwa.",
  memberFromWikipediaNote: "skład z infoboksu Wikipedii — ani MusicBrainz, ani Wikidane nie mają tu nikogo",
  memberFromWikidataNote: "z Wikidanych — MusicBrainz nie ma tej osoby przy tym zespole",
  memberFromDescriptionNote: "z opisu przy artyście w MusicBrainz — relacji członkostwa tam nie ma, jest tylko zdanie",
  roleGuessNote: "instrument dobrany z innych zespołów tej osoby — MusicBrainz nie podaje go przy tym składzie",
  sortNewest: "od najnowszych",
  sortOldest: "chronologicznie",
  dislikeAdd: "Nie moja bajka",
  dislikeActive: "Nie moja bajka ✓",
  genresFromTags: "z tagów MusicBrainz — nikt nie zatwierdził ich jeszcze jako gatunków",
  crewHeading: "Kto to nagrywał",
  crewNote: "Producenci, realizatorzy, mastering i autorzy okładek — z wydań w MusicBrainz. Każde nazwisko to kolejny przystanek: z jego strony widać wszystko, przy czym pracował.",
  crewLoading: "Sprawdzam, kto produkował i kto malował…",
  crewEmpty: "MusicBrainz nie ma przy tych wydaniach nikogo od produkcji ani okładek. To częsta dziura w tej bazie — nie znaczy, że tych ludzi nie było.",
  crewArtwork: "Okładki i zdjęcia",
  crewStudio: "Produkcja i realizacja",
  crewOnAlbums: "przy {n}",
  genresFromWikidata: "gatunki z Wikidanych — MusicBrainz nie ma tu żadnego tagu",
  noGenres: "Ani MusicBrainz, ani Wikidane nie mają gatunku dla tego zespołu. Tyle udało się zebrać.",
  relatedYears: "{years}",
  mbUnavailableWhat: "artysty",
  missingAlbumNotice: "„{title}” nie ma jeszcze w MusicBrainz — dlatego jesteś na stronie artysty, a nie płyty. Bazę uzupełniają ludzie; jeśli znasz tę płytę, możesz ją tam dopisać.",
  missingAlbumAdd: "dopisz w MusicBrainz →",
  personType: "muzyk",
  aka: "aka",
  favoriteActive: "★ Ulubiony",
  favoriteAdd: "☆ Do ulubionych",
  favoritesCount: "{n} w ulubionych",

  bandsHeading: "Zespoły",
  lineupHeading: "Skład",
  playedInBands: "Grał w zespołach",
  currently: "Obecnie",
  formerly: "Dawniej",
  guestOf: "Grał u (koncertowo / sesyjnie)",
  supportMusicians: "Muzycy towarzyszący",
  ownBandHeading: "Jego skład — kto z nim grał",
  ownBandNote: "Artysta solowy to też zespół: pod własnym nazwiskiem nagrywa z konkretnymi ludźmi. Poniżej ci, których MusicBrainz przypisał do jego płyt i tras.",
  albumsWithMember: "płyty z {name} ({n})",

  playedOnHeading: "Grał(a) na płytach",
  playedOnNote: "Wg składów w MusicBrainz — najpierw gościnnie i sesyjnie, potem z własnymi zespołami.",
  withBand: "z {name}",
  guestBadge: "gościnnie",

  albumsHeading: "Albumy",
  epHeading: "EP",
  otherReleases: "Pozostałe wydawnictwa — single, live, kompilacje, dema ({n})",
  noReleases: "MusicBrainz nie ma wydawnictw dla tego artysty.",

  creditsHeading: "Produkcja, realizacja, okładki",
  creditsNote: "Praca przy płytach, która nie jest graniem — w MusicBrainz wisi przy wydaniu, nie przy utworze. Stąd też da się ruszyć w podróż.",
  creditsMoreNote: "Pokazujemy 60 najnowszych z {n}.",

  relatedHeading: "Powiązane zespoły",
  relatedNote: "Liczone z MusicBrainz: przede wszystkim wspólni muzycy, pomocniczo wspólne gatunki. Bez zgadywania — przy każdym zespole widać, co go łączy.",
  relatedShared: "wspólne: {genres}",
  relatedLoading: "Szukam powiązanych zespołów…",

  deepLoading: "Wczytuję dyskografię i skład — przy artystach z długim dorobkiem chwilę to trwa…",

  timeline: {
    roleVocal: "wokal",
    supportingNote: "sesyjnie / koncertowo, nie w składzie",
    supportingShort: "sesyjnie",
    legendSupporting: "cieńszy pasek — współpraca sesyjna lub koncertowa, nie członkostwo",
    unknownNote: "dat nie zna ani MusicBrainz, ani Wikidane",
    legendUnknown: "okres nieznany — wiemy, że grał, nie wiemy kiedy",
    wikidataNote: "daty z Wikidanych",
    legendWikidata: "daty dobrane z Wikidanych, bo MusicBrainz ich nie ma",
    inferredNote: "daty z płyt — MusicBrainz nie ma dat członkostwa",
    legendInferred: "okres odczytany z płyt, nie z dat członkostwa",
    roleGuitar: "gitara",
    roleBass: "bas",
    roleDrums: "perkusja",
    roleKeys: "klawisze",
    roleOther: "inne",
    axisAriaLabel: "Oś czasu",
    lineupSummary: { one: "Oś czasu składu ({n} osoba)", few: "Oś czasu składu ({n} osoby)", many: "Oś czasu składu ({n} osób)" } as { one: string; few?: string; many: string },
    careerSummary: { one: "Oś czasu: gdzie grał(a) {name} ({n} zespół)", few: "Oś czasu: gdzie grał(a) {name} ({n} zespoły)", many: "Oś czasu: gdzie grał(a) {name} ({n} zespołów)" } as { one: string; few?: string; many: string },
    markAlbumLabel: "album — najedź po tytuł, kliknij po stronę płyty",
    markOwnLabel: "płyta pod własnym nazwiskiem",
    legendInSpan: "płyta z jego okresu — kliknij po stronę płyty",
    legendOutSpan: "płyta zespołu spoza jego kadencji",
    footnote: "Z dat członkostwa w MusicBrainz. Brakujące daty rysujemy do dziś — MB nie zawsze ma komplet. Przerwa w pasku to odejście i powrót.",
    today: "dziś",
    outOfSpanSuffix: " — poza jego okresem w składzie",
  },
};
type T = typeof pl;

const en: T = {
  sectionFailed: "The “{name}” section failed to load. The rest of the page is fine — it is only this piece.",
  concertsHeading: "Concerts",
  concertsLoading: "Checking whether and where they play…",
  concertsNone: "Neither MusicBrainz nor Ticketmaster lists upcoming shows for this artist right now. No entry doesn't mean no gigs — small clubs often end up nowhere.",
  concertsNote: "From MusicBrainz and Ticketmaster listings.",
  concertsMine: "Concerts in my cities →",
  topFromPortal: "Highest rated here",
  topFromMb: "Highest rated on MusicBrainz",
  topBadge: "↑ the one above",
  wikiDiscoHeading: "Credits according to Wikipedia",
  wikiDiscoNote: "MusicBrainz attaches production and session credits to individual recordings, and won't hand them over by person — for a producer or session player that comes back empty. This list was written by hand on Wikipedia. The portal hasn't verified it: clicking looks the album up at that moment.",
  wikiDiscoSource: "Source: Wikipedia",
  producedHeading: "Produced, engineered, mastered",
  spotifyOwnNote: "From Spotify — MusicBrainz doesn\u2019t have these releases. Spotify\u2019s catalogue is fuller, but knows nothing about line-ups or production.",
  spotifyGuestNote: "From Spotify — other people\u2019s albums they appear on that MusicBrainz doesn\u2019t know.",
  fromSpotifyNote: "from the Spotify catalogue, matched by artist name",
  producedMore: "Showing the most recent of {n}.",
  producedTracks: "{n} tracks",
  fetchMore: "Fetch more",
  fetchMoreNote: "MusicBrainz returns a hundred entries at a time — this takes a moment.",
  producedNote: "Albums they worked on at the desk rather than with an instrument. From release relationships on MusicBrainz — where production credits usually live.",
  memberFromWikipediaNote: "line-up from the Wikipedia infobox — neither MusicBrainz nor Wikidata has anyone here",
  memberFromWikidataNote: "from Wikidata — MusicBrainz has no such person on this band",
  memberFromDescriptionNote: "from the artist's description in MusicBrainz — there is no membership relation there, only a sentence",
  roleGuessNote: "instrument taken from this person's other bands — MusicBrainz doesn't give one for this line-up",
  sortNewest: "newest first",
  sortOldest: "in order",
  dislikeAdd: "Not my thing",
  dislikeActive: "Not my thing ✓",
  genresFromTags: "from MusicBrainz tags — nobody has promoted them to genres yet",
  crewHeading: "Who recorded it",
  crewNote: "Producers, engineers, mastering and cover artists — from the releases on MusicBrainz. Every name is another stop: their page shows everything they worked on.",
  crewLoading: "Checking who produced and who painted…",
  crewEmpty: "MusicBrainz lists nobody for production or artwork on these releases. That's a common gap in this database — it doesn't mean those people didn't exist.",
  crewArtwork: "Artwork and photography",
  crewStudio: "Production and engineering",
  crewOnAlbums: "on {n}",
  genresFromWikidata: "genres from Wikidata — MusicBrainz has no tag here",
  noGenres: "Neither MusicBrainz nor Wikidata has a genre for this band. This is all we could gather.",
  relatedYears: "{years}",
  mbUnavailableWhat: "an artist",
  missingAlbumNotice: "“{title}” isn't in MusicBrainz yet — that's why you're on the artist's page, not the album's. The database is filled in by people; if you know this record, you can add it there.",
  missingAlbumAdd: "add it to MusicBrainz →",
  personType: "musician",
  aka: "aka",
  favoriteActive: "★ Favourite",
  favoriteAdd: "☆ Add to favourites",
  favoritesCount: "{n} have it in favourites",

  bandsHeading: "Bands",
  lineupHeading: "Lineup",
  playedInBands: "Played in bands",
  currently: "Currently",
  formerly: "Formerly",
  guestOf: "Played with (live / session)",
  supportMusicians: "Touring musicians",
  ownBandHeading: "Their band — who played with them",
  ownBandNote: "A solo artist is a band too: records under their own name are made with particular people. Below are the ones MusicBrainz ties to their albums and tours.",
  albumsWithMember: "albums with {name} ({n})",

  playedOnHeading: "Played on",
  playedOnNote: "By lineup data from MusicBrainz — guest and session credits first, then their own bands.",
  withBand: "with {name}",
  guestBadge: "guest",

  albumsHeading: "Albums",
  epHeading: "EP",
  otherReleases: "Other releases — singles, live albums, compilations, demos ({n})",
  noReleases: "MusicBrainz has no releases for this artist.",

  creditsHeading: "Production, engineering, artwork",
  creditsNote: "Work on records that isn't playing an instrument — MusicBrainz files it against the release, not the recording, so it opens up a trail of its own.",
  creditsMoreNote: "Showing the 60 most recent of {n}.",

  relatedHeading: "Related bands",
  relatedNote: "Worked out from MusicBrainz: shared musicians count most, shared genres are a tiebreaker. No guessing — each band shows exactly what connects it.",
  relatedShared: "shared: {genres}",
  relatedLoading: "Looking for related bands…",

  deepLoading: "Loading the discography and lineup — this can take a moment for artists with a long history…",

  timeline: {
    roleVocal: "vocals",
    supportingNote: "session / live, not a member",
    supportingShort: "session",
    legendSupporting: "thinner bar — session or live work, not membership",
    unknownNote: "neither MusicBrainz nor Wikidata knows the dates",
    legendUnknown: "period unknown — we know they played, not when",
    wikidataNote: "dates from Wikidata",
    legendWikidata: "dates taken from Wikidata, because MusicBrainz has none",
    inferredNote: "dates taken from the albums — MusicBrainz has no membership dates",
    legendInferred: "period read from the albums, not from membership dates",
    roleGuitar: "guitar",
    roleBass: "bass",
    roleDrums: "drums",
    roleKeys: "keys",
    roleOther: "other",
    axisAriaLabel: "Timeline",
    lineupSummary: { one: "Lineup timeline ({n} person)", many: "Lineup timeline ({n} people)" },
    careerSummary: { one: "Timeline: where {name} played ({n} band)", many: "Timeline: where {name} played ({n} bands)" },
    markAlbumLabel: "album — hover for the title, click through to the album",
    markOwnLabel: "album under their own name",
    legendInSpan: "album from their time in the band — click through to it",
    legendOutSpan: "album from outside their time in the band",
    footnote: "From membership dates on MusicBrainz. Missing dates are drawn through to today — MusicBrainz doesn't always have the full record. A gap in a bar means they left and came back.",
    today: "today",
    outOfSpanSuffix: " — outside their time in the lineup",
  },
};

const es: T = {
  sectionFailed: "La sección «{name}» no se ha cargado. El resto de la página funciona — es solo este trozo.",
  concertsHeading: "Conciertos",
  concertsLoading: "Miro si tocan y dónde…",
  concertsNone: "Ni MusicBrainz ni Ticketmaster anuncian ahora conciertos de este artista. Que no haya entrada no significa que no toquen — los clubes pequeños a menudo no aparecen en ningún sitio.",
  concertsNote: "De los anuncios de MusicBrainz y Ticketmaster.",
  concertsMine: "Conciertos en mis ciudades →",
  topFromPortal: "La mejor valorada aquí",
  topFromMb: "La mejor valorada en MusicBrainz",
  topBadge: "↑ la de arriba",
  wikiDiscoHeading: "Trabajos según Wikipedia",
  wikiDiscoNote: "MusicBrainz vincula los créditos de producción y de sesión a grabaciones concretas y no los devuelve por persona: para un productor o un músico de sesión sale vacío. Esta lista está escrita a mano en Wikipedia. El portal no la ha verificado: al pulsar se busca el disco en ese momento.",
  wikiDiscoSource: "Fuente: Wikipedia",
  producedHeading: "Produjo, grabó, masterizó",
  spotifyOwnNote: "De Spotify: MusicBrainz no tiene estos lanzamientos. El catálogo de Spotify es más completo, pero no sabe nada de formaciones ni de producción.",
  spotifyGuestNote: "De Spotify: discos ajenos en los que aparece y que MusicBrainz desconoce.",
  fromSpotifyNote: "del catálogo de Spotify, emparejado por nombre",
  producedMore: "Mostramos los más recientes de {n}.",
  producedTracks: "{n} grabaciones",
  fetchMore: "Cargar más",
  fetchMoreNote: "MusicBrainz devuelve cien entradas por vez: tarda un momento.",
  producedNote: "Discos en los que trabajó desde la mesa, no con un instrumento. De las relaciones de las ediciones en MusicBrainz, donde suelen estar los créditos de producción.",
  memberFromWikipediaNote: "formación del infobox de Wikipedia: ni MusicBrainz ni Wikidata tienen a nadie aquí",
  memberFromWikidataNote: "de Wikidata: MusicBrainz no tiene a esta persona en esta banda",
  memberFromDescriptionNote: "de la descripción del artista en MusicBrainz: allí no hay relación de pertenencia, solo una frase",
  roleGuessNote: "instrumento tomado de sus otras bandas — MusicBrainz no da ninguno para esta formación",
  sortNewest: "más nuevos primero",
  sortOldest: "en orden",
  dislikeAdd: "No es lo mío",
  dislikeActive: "No es lo mío ✓",
  genresFromTags: "de las etiquetas de MusicBrainz — todavía nadie las ha aprobado como géneros",
  crewHeading: "Quién lo grabó",
  crewNote: "Productores, técnicos, masterización y autores de portada — de las ediciones en MusicBrainz. Cada nombre es otra parada: en su página está todo en lo que trabajó.",
  crewLoading: "Mirando quién produjo y quién pintó…",
  crewEmpty: "MusicBrainz no tiene a nadie de producción ni de portada en estas ediciones. Es un hueco habitual de esta base — no significa que esa gente no existiera.",
  crewArtwork: "Portadas y fotografía",
  crewStudio: "Producción y grabación",
  crewOnAlbums: "en {n}",
  genresFromWikidata: "géneros de Wikidata — MusicBrainz no tiene ninguna etiqueta aquí",
  noGenres: "Ni MusicBrainz ni Wikidata tienen género para esta banda. Esto es todo lo que hemos podido reunir.",
  relatedYears: "{years}",
  mbUnavailableWhat: "un artista",
  missingAlbumNotice: "«{title}» todavía no está en MusicBrainz: por eso estás en la página del artista y no en la del disco. La base la rellenan personas; si conoces este disco, puedes añadirlo allí.",
  missingAlbumAdd: "añádelo a MusicBrainz →",
  personType: "músico",
  aka: "alias",
  favoriteActive: "★ Favorito",
  favoriteAdd: "☆ Añadir a favoritos",
  favoritesCount: "{n} lo tienen en favoritos",

  bandsHeading: "Bandas",
  lineupHeading: "Formación",
  playedInBands: "Tocó en bandas",
  currently: "Actualmente",
  formerly: "Anteriormente",
  guestOf: "Tocó con (en directo / de sesión)",
  supportMusicians: "Músicos de gira",
  ownBandHeading: "Su banda — quién tocó con él",
  ownBandNote: "Un artista en solitario también es una banda: los discos a su nombre se graban con gente concreta. Abajo, quienes MusicBrainz asocia a sus discos y giras.",
  albumsWithMember: "discos con {name} ({n})",

  playedOnHeading: "Discos en los que tocó",
  playedOnNote: "Según las formaciones de MusicBrainz — primero colaboraciones y sesiones, luego sus propias bandas.",
  withBand: "con {name}",
  guestBadge: "invitado",

  albumsHeading: "Álbumes",
  epHeading: "EP",
  otherReleases: "Otros lanzamientos — sencillos, directos, recopilatorios, demos ({n})",
  noReleases: "MusicBrainz no tiene lanzamientos de este artista.",

  creditsHeading: "Producción, ingeniería, portadas",
  creditsNote: "Trabajo en discos que no es tocar un instrumento — MusicBrainz lo registra en el lanzamiento, no en la grabación, así que también abre su propio camino.",
  creditsMoreNote: "Mostrando los 60 más recientes de {n}.",

  relatedHeading: "Bandas relacionadas",
  relatedNote: "Calculado a partir de MusicBrainz: sobre todo músicos en común, y como criterio secundario, géneros compartidos. Sin adivinar — cada banda muestra exactamente qué la conecta.",
  relatedShared: "en común: {genres}",
  relatedLoading: "Buscando bandas relacionadas…",

  deepLoading: "Cargando discografía y formación — con artistas de trayectoria larga puede tardar un momento…",

  timeline: {
    roleVocal: "voz",
    supportingNote: "de sesión / en directo, no miembro",
    supportingShort: "sesión",
    legendSupporting: "barra más fina: trabajo de sesión o en directo, no militancia",
    unknownNote: "ni MusicBrainz ni Wikidata conocen las fechas",
    legendUnknown: "periodo desconocido — sabemos que tocó, no cuándo",
    wikidataNote: "fechas de Wikidata",
    legendWikidata: "fechas tomadas de Wikidata, porque MusicBrainz no las tiene",
    inferredNote: "fechas tomadas de los discos — MusicBrainz no tiene fechas de pertenencia",
    legendInferred: "periodo deducido de los discos, no de las fechas de pertenencia",
    roleGuitar: "guitarra",
    roleBass: "bajo",
    roleDrums: "batería",
    roleKeys: "teclados",
    roleOther: "otros",
    axisAriaLabel: "Línea temporal",
    lineupSummary: { one: "Línea temporal de la formación ({n} persona)", many: "Línea temporal de la formación ({n} personas)" },
    careerSummary: { one: "Línea temporal: dónde tocó {name} ({n} banda)", many: "Línea temporal: dónde tocó {name} ({n} bandas)" },
    markAlbumLabel: "álbum — pasa el ratón para ver el título, haz clic para ir a él",
    markOwnLabel: "álbum a su propio nombre",
    legendInSpan: "álbum de su etapa en la banda — haz clic para ir a él",
    legendOutSpan: "álbum fuera de su etapa en la banda",
    footnote: "Según las fechas de pertenencia en MusicBrainz. Las fechas que faltan se dibujan hasta hoy — MusicBrainz no siempre tiene el dato completo. Un hueco en la barra significa que se fue y volvió.",
    today: "hoy",
    outOfSpanSuffix: " — fuera de su etapa en la formación",
  },
};

const de: T = {
  sectionFailed: "Der Abschnitt „{name}“ konnte nicht geladen werden. Der Rest der Seite läuft — es ist nur dieses Stück.",
  concertsHeading: "Konzerte",
  concertsLoading: "Schaue nach, ob und wo sie spielen…",
  concertsNone: "Weder MusicBrainz noch Ticketmaster kennt gerade Termine dieses Artists. Kein Eintrag heißt nicht, dass nichts läuft — kleine Clubs tauchen oft nirgends auf.",
  concertsNote: "Aus den Ankündigungen von MusicBrainz und Ticketmaster.",
  concertsMine: "Konzerte in meinen Städten →",
  topFromPortal: "Hier am besten bewertet",
  topFromMb: "Bei MusicBrainz am besten bewertet",
  topBadge: "↑ die von oben",
  wikiDiscoHeading: "Werke laut Wikipedia",
  wikiDiscoNote: "MusicBrainz hängt Produktions- und Session-Credits an einzelne Aufnahmen und gibt sie nicht pro Person heraus — bei Produzenten und Session-Musikern kommt nichts zurück. Diese Liste stammt von Hand aus Wikipedia. Das Portal hat sie nicht geprüft: der Klick sucht das Album erst in diesem Moment.",
  wikiDiscoSource: "Quelle: Wikipedia",
  producedHeading: "Produziert, aufgenommen, gemastert",
  spotifyOwnNote: "Von Spotify — diese Veröffentlichungen kennt MusicBrainz nicht. Spotifys Katalog ist vollständiger, weiß aber nichts über Besetzungen oder Produktion.",
  spotifyGuestNote: "Von Spotify — fremde Alben, auf denen die Person auftaucht und die MusicBrainz nicht kennt.",
  fromSpotifyNote: "aus dem Spotify-Katalog, über den Namen zugeordnet",
  producedMore: "Wir zeigen die neuesten von {n}.",
  producedTracks: "{n} Aufnahmen",
  fetchMore: "Weitere laden",
  fetchMoreNote: "MusicBrainz liefert hundert Einträge auf einmal — das dauert einen Moment.",
  producedNote: "Alben, an denen er am Pult gearbeitet hat, nicht am Instrument. Aus den Beziehungen der Veröffentlichungen bei MusicBrainz — dort stehen Produktionscredits üblicherweise.",
  memberFromWikipediaNote: "Besetzung aus der Wikipedia-Infobox — weder MusicBrainz noch Wikidata haben hier jemanden",
  memberFromWikidataNote: "aus Wikidata — MusicBrainz kennt diese Person bei dieser Band nicht",
  memberFromDescriptionNote: "aus der Künstlerbeschreibung in MusicBrainz — dort gibt es keine Mitgliedschaftsrelation, nur einen Satz",
  roleGuessNote: "Instrument aus den anderen Bands dieser Person — MusicBrainz nennt für diese Besetzung keines",
  sortNewest: "neueste zuerst",
  sortOldest: "chronologisch",
  dislikeAdd: "Nicht mein Ding",
  dislikeActive: "Nicht mein Ding ✓",
  genresFromTags: "aus MusicBrainz-Tags — noch niemand hat sie als Genres bestätigt",
  crewHeading: "Wer es aufgenommen hat",
  crewNote: "Produzenten, Toningenieure, Mastering und Cover-Künstler — aus den Veröffentlichungen bei MusicBrainz. Jeder Name ist die nächste Station: auf seiner Seite steht alles, woran er gearbeitet hat.",
  crewLoading: "Schaue nach, wer produziert und wer gemalt hat…",
  crewEmpty: "MusicBrainz führt bei diesen Veröffentlichungen niemanden für Produktion oder Artwork. Eine übliche Lücke dieser Datenbank — es heißt nicht, dass es diese Leute nicht gab.",
  crewArtwork: "Artwork und Fotografie",
  crewStudio: "Produktion und Aufnahme",
  crewOnAlbums: "bei {n}",
  genresFromWikidata: "Genres aus Wikidata — MusicBrainz hat hier kein Tag",
  noGenres: "Weder MusicBrainz noch Wikidata kennt ein Genre für diese Band. Mehr war nicht zu holen.",
  relatedYears: "{years}",
  mbUnavailableWhat: "eines Künstlers",
  missingAlbumNotice: "„{title}“ steht noch nicht in MusicBrainz — deshalb bist du auf der Künstlerseite und nicht beim Album. Die Datenbank füllen Menschen; wenn du diese Platte kennst, kannst du sie dort eintragen.",
  missingAlbumAdd: "in MusicBrainz eintragen →",
  personType: "Musiker",
  aka: "auch bekannt als",
  favoriteActive: "★ Favorit",
  favoriteAdd: "☆ Zu Favoriten",
  favoritesCount: "{n} haben es in den Favoriten",

  bandsHeading: "Bands",
  lineupHeading: "Besetzung",
  playedInBands: "Spielte in Bands",
  currently: "Aktuell",
  formerly: "Früher",
  guestOf: "Spielte bei (live / als Session-Musiker)",
  supportMusicians: "Begleitmusiker",
  ownBandHeading: "Seine Band — wer mit ihm spielte",
  ownBandNote: "Ein Soloartist ist auch eine Band: Platten unter eigenem Namen entstehen mit konkreten Leuten. Unten die, die MusicBrainz seinen Alben und Touren zuordnet.",
  albumsWithMember: "Alben mit {name} ({n})",

  playedOnHeading: "Mitgewirkt auf",
  playedOnNote: "Nach Besetzungsdaten von MusicBrainz — zuerst Gast- und Session-Auftritte, dann die eigenen Bands.",
  withBand: "mit {name}",
  guestBadge: "Gast",

  albumsHeading: "Alben",
  epHeading: "EP",
  otherReleases: "Weitere Veröffentlichungen — Singles, Livealben, Kompilationen, Demos ({n})",
  noReleases: "MusicBrainz hat keine Veröffentlichungen für diesen Künstler.",

  creditsHeading: "Produktion, Technik, Artwork",
  creditsNote: "Arbeit an Alben, die kein Instrumentalspiel ist — MusicBrainz führt sie beim Release, nicht bei der Aufnahme, und eröffnet damit einen eigenen Pfad.",
  creditsMoreNote: "Die 60 neuesten von {n} werden angezeigt.",

  relatedHeading: "Verwandte Bands",
  relatedNote: "Aus MusicBrainz errechnet: vor allem gemeinsame Musiker, ergänzend gemeinsame Genres. Ohne Raten — bei jeder Band ist zu sehen, was sie verbindet.",
  relatedShared: "gemeinsam: {genres}",
  relatedLoading: "Suche verwandte Bands…",

  deepLoading: "Lade Diskografie und Besetzung — bei Künstlern mit langer Geschichte dauert das einen Moment…",

  timeline: {
    roleVocal: "Gesang",
    supportingNote: "Session / live, kein Mitglied",
    supportingShort: "Session",
    legendSupporting: "dünnerer Balken — Session- oder Livearbeit, keine Mitgliedschaft",
    unknownNote: "weder MusicBrainz noch Wikidata kennt die Daten",
    legendUnknown: "Zeitraum unbekannt — wir wissen, dass er spielte, nicht wann",
    wikidataNote: "Daten aus Wikidata",
    legendWikidata: "Daten aus Wikidata, weil MusicBrainz keine hat",
    inferredNote: "Daten aus den Alben — MusicBrainz hat keine Mitgliedsdaten",
    legendInferred: "Zeitraum aus den Alben abgelesen, nicht aus Mitgliedsdaten",
    roleGuitar: "Gitarre",
    roleBass: "Bass",
    roleDrums: "Schlagzeug",
    roleKeys: "Keyboard",
    roleOther: "sonstige",
    axisAriaLabel: "Zeitleiste",
    lineupSummary: { one: "Besetzungs-Zeitleiste ({n} Person)", many: "Besetzungs-Zeitleiste ({n} Personen)" },
    careerSummary: { one: "Zeitleiste: wo {name} spielte ({n} Band)", many: "Zeitleiste: wo {name} spielte ({n} Bands)" },
    markAlbumLabel: "Album — Titel per Hover ansehen, Klick führt zum Album",
    markOwnLabel: "Album unter eigenem Namen",
    legendInSpan: "Album aus seiner/ihrer Zeit in der Band — Klick führt dorthin",
    legendOutSpan: "Album außerhalb seiner/ihrer Zeit in der Band",
    footnote: "Nach Mitgliedschaftsdaten von MusicBrainz. Fehlende Daten werden bis heute gezeichnet — MusicBrainz hat nicht immer alles. Eine Lücke im Balken bedeutet Ausstieg und Rückkehr.",
    today: "heute",
    outOfSpanSuffix: " — außerhalb der Zeit in der Besetzung",
  },
};

export const artist: Record<Locale, T> = { pl, en, es, de };
