/**
 * Ekran „Pogadajmy o muzyce".
 *
 * Odwrotność „podróży w nieznane", która z jednego zdania robiła od razu
 * zamkniętą listę. Tu każda odpowiedź jest WYNIKIEM SZUKANIA: płyty można
 * pooglądać, dopytać o coś innego, zawęzić — a podróż zrobić dopiero wtedy,
 * gdy człowiek uzna, że warto. Lista jest efektem rozmowy, nie jej początkiem.
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  eyebrow: "Podróż",
  title: "W nieznane",
  lead: "Reszta portalu wie, dokąd jedziesz — ta jedna nie. Napisz, czego chcesz posłuchać, a dostaniesz płyty: sprawdzone w MusicBrainz, więc w każdą da się wejść. Możesz dopytywać do skutku, a na końcu zrobić z tego podróż.",
  label: "Twoja wiadomość",
  placeholder: "Czego szukasz? Możesz dopytywać, zawężać, prosić o coś zupełnie innego…",
  send: "Wyślij",
  cta: "Rusz w nieznane",
  working: "Szukam płyt i sprawdzam każdą w MusicBrainz",
  workingShort: "Szukam…",
  leaveOk: "Możesz stąd wyjść — odpowiedź czeka pod tym adresem.",
  youAsked: "Pytasz",
  copy: "Skopiuj",
  copied: "Skopiowane",
  again: "Odtwórz jeszcze raz",
  stepSearching: "Szukam płyt",
  stepChecking: "Sprawdzam w MusicBrainz",
  stepHave: "Jest",
  stepMissing: "Nie ma w MusicBrainz",
  found: "Znalezione płyty",
  dropped: "Pominięte, bo MusicBrainz ich nie zna: {n}",
  makeJourney: "Zrób z tego podróż",
  makeJourneyNote: "Zapisze wszystkie płyty z tej rozmowy jako podróż — z ocenianiem i odhaczaniem.",
  journeyTitle: "Z rozmowy",
  newChat: "Nowa rozmowa",
  yours: "Twoje rozmowy",
  empty: "Jeszcze nie rozmawialiśmy. Zacznij od czegokolwiek — nastroju, zespołu, płyty, której masz dość.",
  gone: "Nie mam już tej rozmowy. Trzymamy je dobę.",
  loginRest: ", żeby pogadać — rozmowa zapisuje się na Twoim koncie.",
  noKey: "Ten ekran potrzebuje klucza do modelu językowego. Bez niego reszta portalu działa normalnie.",
  honestNote: "Każdą płytę portal potwierdza w MusicBrainz — czego nie potwierdzi, nie zobaczysz.",
  examplesLabel: "Na przykład",
  exPrime: "Coś w klimacie wczesnego Voivoda, ale nagranego po 2010.",
  exSecond: "Jazz na trąbkę, który nie jest tłem. Chcę usłyszeć pomieszczenie.",
  exThird: "Mam dość melodyjnego death metalu. Daj coś brzydszego.",
  errors: {
    krotki: "Napisz trochę więcej — z dwóch słów nic nie wyciągnę.",
    limit: "Na dziś koniec — {n} pytań dziennie. Każde szukanie kosztuje. Wróć jutro.",
    brakKlucza: "Model nie jest skonfigurowany.",
    model: "Nie udało się nic wyszukać. Spróbuj jeszcze raz za chwilę.",
    mbAwaria: "MusicBrainz chwilowo nie odpowiada, więc nie mam czym potwierdzić płyt.",
    nieznany: "Coś poszło nie tak. Spróbuj jeszcze raz.",
  } as Record<string, string>,
};
type T = typeof pl;

const en: T = {
  eyebrow: "Journey",
  title: "Into the unknown",
  lead: "The rest of the portal knows where you're going — this one doesn't. Write what you feel like hearing and you get albums: checked against MusicBrainz, so every one opens. Keep asking as long as you like, then turn it into a journey.",
  label: "Your message",
  placeholder: "What are you after? Ask follow-ups, narrow it down, change direction…",
  send: "Send",
  cta: "Set off",
  working: "Looking for albums and checking each one against MusicBrainz",
  workingShort: "Searching…",
  leaveOk: "You can leave this page — the answer will be waiting at this address.",
  youAsked: "You asked",
  copy: "Copy",
  copied: "Copied",
  again: "Run it again",
  stepSearching: "Looking for albums",
  stepChecking: "Checking MusicBrainz",
  stepHave: "Got it",
  stepMissing: "Not in MusicBrainz",
  found: "Albums found",
  dropped: "Left out because MusicBrainz doesn't have them: {n}",
  makeJourney: "Turn this into a journey",
  makeJourneyNote: "Saves every album from this conversation as a journey — with ratings and ticking off.",
  journeyTitle: "From a conversation",
  newChat: "New conversation",
  yours: "Your conversations",
  empty: "We haven't talked yet. Start anywhere — a mood, a band, something you've had enough of.",
  gone: "That conversation is gone. We keep them for a day.",
  loginRest: " to talk — the conversation is saved to your account.",
  noKey: "This screen needs a language-model key. Without it the rest of the portal works as usual.",
  honestNote: "The portal confirms every album against MusicBrainz — anything it can't confirm, you won't see.",
  examplesLabel: "For example",
  exPrime: "Something like early Voivod, but recorded after 2010.",
  exSecond: "Trumpet jazz that isn't background. I want to hear the room.",
  exThird: "I'm tired of melodic death metal. Give me something uglier.",
  errors: {
    krotki: "Write a bit more — two words aren't enough to go on.",
    limit: "That's it for today — {n} questions a day. Every search costs money. Come back tomorrow.",
    brakKlucza: "The model isn't configured.",
    model: "The search came back with nothing. Try again in a moment.",
    mbAwaria: "MusicBrainz isn't answering, so there's nothing to confirm the albums against.",
    nieznany: "Something went wrong. Try again.",
  },
};

const es: T = {
  eyebrow: "Viaje",
  title: "Hacia lo desconocido",
  lead: "El resto del portal sabe adónde vas; este no. Escribe qué te apetece escuchar y recibirás discos comprobados en MusicBrainz, así que todos se abren. Pregunta lo que haga falta y al final conviértelo en un viaje.",
  label: "Tu mensaje",
  placeholder: "¿Qué buscas? Puedes repreguntar, acotar o cambiar de rumbo…",
  send: "Enviar",
  cta: "Zarpar",
  working: "Busco discos y compruebo cada uno en MusicBrainz",
  workingShort: "Buscando…",
  leaveOk: "Puedes salir de aquí: la respuesta te esperará en esta dirección.",
  youAsked: "Preguntas",
  copy: "Copiar",
  copied: "Copiado",
  again: "Repetir la búsqueda",
  stepSearching: "Busco discos",
  stepChecking: "Compruebo en MusicBrainz",
  stepHave: "Está",
  stepMissing: "No está en MusicBrainz",
  found: "Discos encontrados",
  dropped: "Descartados porque MusicBrainz no los tiene: {n}",
  makeJourney: "Convertir en viaje",
  makeJourneyNote: "Guarda todos los discos de esta conversación como un viaje, con notas y seguimiento.",
  journeyTitle: "De una conversación",
  newChat: "Nueva conversación",
  yours: "Tus conversaciones",
  empty: "Todavía no hemos hablado. Empieza por donde quieras: un ánimo, un grupo, algo de lo que estés harto.",
  gone: "Esa conversación ya no está. Las guardamos un día.",
  loginRest: " para hablar: la conversación se guarda en tu cuenta.",
  noKey: "Esta pantalla necesita una clave de modelo de lenguaje. Sin ella el resto del portal funciona igual.",
  honestNote: "El portal confirma cada disco en MusicBrainz: lo que no se confirme, no lo verás.",
  examplesLabel: "Por ejemplo",
  exPrime: "Algo parecido a los primeros Voivod, pero grabado después de 2010.",
  exSecond: "Jazz de trompeta que no sea de fondo. Quiero oír la sala.",
  exThird: "Estoy harto del death metal melódico. Dame algo más feo.",
  errors: {
    krotki: "Escribe un poco más: con dos palabras no puedo sacar nada.",
    limit: "Por hoy basta: {n} preguntas al día. Cada búsqueda cuesta. Vuelve mañana.",
    brakKlucza: "El modelo no está configurado.",
    model: "La búsqueda no devolvió nada. Inténtalo de nuevo en un momento.",
    mbAwaria: "MusicBrainz no responde, así que no tengo con qué confirmar los discos.",
    nieznany: "Algo salió mal. Inténtalo de nuevo.",
  },
};

const de: T = {
  eyebrow: "Reise",
  title: "Ins Unbekannte",
  lead: "Der Rest des Portals weiß, wohin du willst — dieser Teil nicht. Schreib, wonach dir ist, und du bekommst Alben: bei MusicBrainz geprüft, also lässt sich jedes öffnen. Frag so lange nach, wie du magst, und mach am Ende eine Reise daraus.",
  label: "Deine Nachricht",
  placeholder: "Was suchst du? Nachfragen, eingrenzen, Richtung wechseln — alles möglich…",
  send: "Senden",
  cta: "Aufbrechen",
  working: "Ich suche Alben und prüfe jedes über MusicBrainz",
  workingShort: "Suche…",
  leaveOk: "Du kannst die Seite verlassen — die Antwort wartet unter dieser Adresse.",
  youAsked: "Du fragst",
  copy: "Kopieren",
  copied: "Kopiert",
  again: "Noch einmal suchen",
  stepSearching: "Ich suche Alben",
  stepChecking: "Prüfe bei MusicBrainz",
  stepHave: "Vorhanden",
  stepMissing: "Nicht bei MusicBrainz",
  found: "Gefundene Alben",
  dropped: "Weggelassen, weil MusicBrainz sie nicht kennt: {n}",
  makeJourney: "Daraus eine Reise machen",
  makeJourneyNote: "Speichert alle Alben aus diesem Gespräch als Reise — mit Bewerten und Abhaken.",
  journeyTitle: "Aus einem Gespräch",
  newChat: "Neues Gespräch",
  yours: "Deine Gespräche",
  empty: "Wir haben noch nicht geredet. Fang irgendwo an: eine Stimmung, eine Band, etwas, wovon du genug hast.",
  gone: "Dieses Gespräch gibt es nicht mehr. Wir halten sie einen Tag.",
  loginRest: ", um zu reden — das Gespräch wird in deinem Konto gespeichert.",
  noKey: "Dieser Bildschirm braucht einen Schlüssel für das Sprachmodell. Ohne ihn läuft der Rest des Portals wie gewohnt.",
  honestNote: "Das Portal bestätigt jedes Album über MusicBrainz — was sich nicht bestätigen lässt, siehst du nicht.",
  examplesLabel: "Zum Beispiel",
  exPrime: "Etwas wie die frühen Voivod, aber nach 2010 aufgenommen.",
  exSecond: "Trompeten-Jazz, der kein Hintergrund ist. Ich will den Raum hören.",
  exThird: "Ich habe genug von melodischem Death Metal. Gib mir etwas Hässlicheres.",
  errors: {
    krotki: "Schreib etwas mehr — aus zwei Wörtern lässt sich nichts holen.",
    limit: "Für heute Schluss — {n} Fragen pro Tag. Jede Suche kostet. Komm morgen wieder.",
    brakKlucza: "Das Modell ist nicht konfiguriert.",
    model: "Die Suche hat nichts ergeben. Versuch es gleich noch einmal.",
    mbAwaria: "MusicBrainz antwortet gerade nicht, also fehlt die Bestätigung für die Alben.",
    nieznany: "Etwas ist schiefgegangen. Versuch es noch einmal.",
  },
};

export const chat: Record<Locale, T> = { pl, en, es, de };
