/** Napisy ekranu: concerts. Polski jest źródłem prawdy — z niego bierzemy typ. */
import type { Locale } from "@/lib/i18n";

const pl = {
  myGenresChip: "Moje gatunki",
  otherGenresLabel: "poza moimi",
  hiddenOffGenre: "Schowałam {n} koncertów spoza Twoich gatunków — Ticketmaster traktuje gatunek jak podpowiedź, nie filtr.",
  showOffGenre: "pokaż wszystko",
  hideOffGenre: "pokaż tylko moje gatunki",
  title: "Koncerty",
  heroTitle: "Co gra w okolicy",
  loginIntro: "i wskaż w profilu miasta albo kraje, które Cię interesują — pokażę koncerty na najbliższe trzy miesiące, w Twoich gatunkach i z Twoich ulubionych zespołów.",
  setAreas: "Ustaw swoje obszary",
  inYourGenres: "W Twoich gatunkach",
  inYourGenresIntro: "Z listy „dla moich gatunków” w profilu.",
  tmWithKey: "Ticketmaster filtruje po Twoich kategoriach (waga 3+), MusicBrainz dokłada, co wie o tych miastach.",
  tmWithoutKey: "Bez klucza do Ticketmastera lecimy na samym MusicBrainz — a ten nie zna gatunków wydarzeń, więc to wszystko, co ma o tych miastach.",
  changeAreas: "Zmień obszary",
  noAreasYet: "Nie masz jeszcze żadnego obszaru.",
  addCityOrCountry: "Dodaj miasto albo kraj",
  addAreaTail: ", a pokażę, co tam gra.",
  loadingAreaConcerts: "Sprawdzam, co gra w Twoich miastach…",
  favoriteBands: "Twoje ulubione zespoły",
  narrowedTo: "Zawężone do listy „dla ulubionych”: {areas}.",
  noNarrowing: "Bez zawężenia — jeśli zespół z gwiazdką gdziekolwiek gra i MusicBrainz o tym wie, zobaczysz to tutaj.",
  noFavoritesYet: "Nie masz jeszcze ulubionych zespołów — oznacz je gwiazdką na stronie zespołu.",
  loadingFavoriteConcerts: "Pytam o trasy Twoich zespołów…",
  nothingInAreas: "Nic nie znalazłam w Twoich obszarach na najbliższe trzy miesiące.",
  mbNotAnAgenda: " MusicBrainz to katalog nagrań, nie afisz koncertowy — zapowiedzi ma niewiele.",
  nothingInGenre: "Nic w tym gatunku w Twoich obszarach.",
  showAll: "Pokaż wszystko",
  noFavoriteConcerts: "MusicBrainz nie ma zapowiedzi Twoich ulubionych zespołów na ten okres.",
  fromFavorites: "z Twoich ulubionych:",
  listenBefore: "posłuchaj przed koncertem:",
  wholeCountry: "cały kraj: {country}",
};
type T = typeof pl;

const en: T = {
  myGenresChip: "My genres",
  otherGenresLabel: "outside mine",
  hiddenOffGenre: "Hidden {n} concerts outside your genres — Ticketmaster treats genre as a hint, not a filter.",
  showOffGenre: "show everything",
  hideOffGenre: "show only my genres",
  title: "Concerts",
  heroTitle: "What's on nearby",
  loginIntro: "and set the cities or countries you care about in your profile — I'll show concerts for the next three months, in your genres and from your favourite bands.",
  setAreas: "Set your areas",
  inYourGenres: "In your genres",
  inYourGenresIntro: "From the “for my genres” list in your profile.",
  tmWithKey: "Ticketmaster filters by your categories (weight 3+), MusicBrainz adds whatever it knows about those cities.",
  tmWithoutKey: "No Ticketmaster key, so we're running on MusicBrainz alone — and it doesn't know event genres, so this is everything it has on these cities.",
  changeAreas: "Change areas",
  noAreasYet: "You don't have any area set yet.",
  addCityOrCountry: "Add a city or country",
  addAreaTail: " and I'll show you what's playing there.",
  loadingAreaConcerts: "Checking what's on in your cities…",
  favoriteBands: "Your favourite bands",
  narrowedTo: "Narrowed to the “for favourites” list: {areas}.",
  noNarrowing: "No narrowing — if a starred band is playing anywhere and MusicBrainz knows about it, you'll see it here.",
  noFavoritesYet: "You don't have any favourite bands yet — star one on its band page.",
  loadingFavoriteConcerts: "Checking your bands' tours…",
  nothingInAreas: "Nothing found in your areas for the next three months.",
  mbNotAnAgenda: " MusicBrainz is a recordings catalogue, not a gig guide — it has few upcoming shows.",
  nothingInGenre: "Nothing in that genre in your areas.",
  showAll: "Show everything",
  noFavoriteConcerts: "MusicBrainz has no upcoming shows for your favourite bands in this period.",
  fromFavorites: "from your favourites:",
  listenBefore: "listen before you go:",
  wholeCountry: "whole country: {country}",
};

const es: T = {
  myGenresChip: "Mis géneros",
  otherGenresLabel: "fuera de los míos",
  hiddenOffGenre: "He ocultado {n} conciertos fuera de tus géneros — Ticketmaster trata el género como una pista, no como un filtro.",
  showOffGenre: "mostrar todo",
  hideOffGenre: "mostrar solo mis géneros",
  title: "Conciertos",
  heroTitle: "Qué suena por aquí",
  loginIntro: "e indica en tu perfil las ciudades o países que te interesan — te enseñaré los conciertos de los próximos tres meses, en tus géneros y de tus bandas favoritas.",
  setAreas: "Configura tus zonas",
  inYourGenres: "En tus géneros",
  inYourGenresIntro: "De la lista «para mis géneros» del perfil.",
  tmWithKey: "Ticketmaster filtra por tus categorías (peso 3+), y MusicBrainz añade lo que sepa de esas ciudades.",
  tmWithoutKey: "Sin clave de Ticketmaster vamos solo con MusicBrainz — y este no conoce géneros de eventos, así que es todo lo que tiene sobre esas ciudades.",
  changeAreas: "Cambiar zonas",
  noAreasYet: "Todavía no tienes ninguna zona.",
  addCityOrCountry: "Añade una ciudad o un país",
  addAreaTail: " y te enseñaré qué se toca allí.",
  loadingAreaConcerts: "Comprobando qué suena en tus ciudades…",
  favoriteBands: "Tus bandas favoritas",
  narrowedTo: "Limitado a la lista «para favoritos»: {areas}.",
  noNarrowing: "Sin límite — si una banda marcada con estrella toca en cualquier sitio y MusicBrainz lo sabe, lo verás aquí.",
  noFavoritesYet: "Todavía no tienes bandas favoritas — márcalas con una estrella en su página.",
  loadingFavoriteConcerts: "Preguntando por las giras de tus bandas…",
  nothingInAreas: "No he encontrado nada en tus zonas para los próximos tres meses.",
  mbNotAnAgenda: " MusicBrainz es un catálogo de grabaciones, no una cartelera — tiene pocos anuncios.",
  nothingInGenre: "Nada de este género en tus zonas.",
  showAll: "Mostrar todo",
  noFavoriteConcerts: "MusicBrainz no tiene anuncios de tus bandas favoritas para este periodo.",
  fromFavorites: "de tus favoritos:",
  listenBefore: "escúchalo antes de ir:",
  wholeCountry: "todo el país: {country}",
};

const de: T = {
  myGenresChip: "Meine Genres",
  otherGenresLabel: "außerhalb meiner",
  hiddenOffGenre: "{n} Konzerte außerhalb deiner Genres ausgeblendet — Ticketmaster versteht das Genre als Hinweis, nicht als Filter.",
  showOffGenre: "alles anzeigen",
  hideOffGenre: "nur meine Genres",
  title: "Konzerte",
  heroTitle: "Was hier los ist",
  loginIntro: "und gib in deinem Profil die Städte oder Länder an, die dich interessieren — ich zeige dir Konzerte für die nächsten drei Monate, in deinen Genres und von deinen Lieblingsbands.",
  setAreas: "Deine Regionen festlegen",
  inYourGenres: "In deinen Genres",
  inYourGenresIntro: "Aus der Liste „für meine Genres“ im Profil.",
  tmWithKey: "Ticketmaster filtert nach deinen Kategorien (Gewicht 3+), MusicBrainz ergänzt, was es über diese Städte weiß.",
  tmWithoutKey: "Ohne Ticketmaster-Schlüssel läuft es nur über MusicBrainz — und das kennt keine Genres bei Veranstaltungen, also ist das alles, was es zu diesen Städten hat.",
  changeAreas: "Regionen ändern",
  noAreasYet: "Du hast noch keine Region festgelegt.",
  addCityOrCountry: "Füge eine Stadt oder ein Land hinzu",
  addAreaTail: ", dann zeige ich dir, was dort läuft.",
  loadingAreaConcerts: "Ich schaue nach, was in deinen Städten läuft…",
  favoriteBands: "Deine Lieblingsbands",
  narrowedTo: "Eingegrenzt auf die Liste „für Favoriten“: {areas}.",
  noNarrowing: "Ohne Eingrenzung — wenn eine markierte Band irgendwo spielt und MusicBrainz davon weiß, siehst du es hier.",
  noFavoritesYet: "Du hast noch keine Lieblingsbands — markiere sie mit einem Stern auf der Bandseite.",
  loadingFavoriteConcerts: "Ich frage nach den Touren deiner Bands…",
  nothingInAreas: "Für die nächsten drei Monate habe ich in deinen Regionen nichts gefunden.",
  mbNotAnAgenda: " MusicBrainz ist ein Aufnahmenkatalog, kein Veranstaltungskalender — es hat nur wenige Ankündigungen.",
  nothingInGenre: "Nichts in diesem Genre in deinen Regionen.",
  showAll: "Alles anzeigen",
  noFavoriteConcerts: "MusicBrainz hat für diesen Zeitraum keine Ankündigungen zu deinen Lieblingsbands.",
  fromFavorites: "aus deinen Favoriten:",
  listenBefore: "vorher reinhören:",
  wholeCountry: "ganzes Land: {country}",
};

export const concerts: Record<Locale, T> = { pl, en, es, de };
