/** Napisy ekranu: home. Polski jest źródłem prawdy — z niego bierzemy typ. */
import type { Locale } from "@/lib/i18n";

const pl = {
  lineupTitle: "Zmiany w składach",
  lineupNote: "Z dat członkostwa w MusicBrainz — ostatnie półtora roku. ★ to Twoi ulubieni artyści.",
  lineupEmpty: "Nie masz jeszcze ulubionych artystów. Postaw gwiazdkę na stronie dowolnego, a tutaj zobaczysz, kto wszedł do składu i kto z niego odszedł.",
  lineupNoNews: "U Twoich ulubionych artystów nic się ostatnio nie zmieniło w składach — przynajmniej nic, co trafiło do MusicBrainz.",
  joined: "dołączył(a) do",
  left: "odszedł(-ła) z",
  lineupLoading: "Sprawdzam zmiany w składach…",
  heroTitle: "Podróż po muzyce",
  heroTextBefore: "Twoja podróż z muzyką zaczyna się tutaj. Zanurz się w tym wspaniałym świecie, podróżuj ",
  heroTextBold: "odwiedzając artystów i ich kolejne przystanie",
  heroTextAfter: ". Zapraszamy.",
  loginCta: "Zaloguj się",
  loginPromptRest: ", żeby ustawić preferencje, oceniać i komentować.",
  releasesForYou: "Premiery dla Ciebie",
  releasesThisWeek: "Premiery tygodnia",
  allReleases: "wszystkie →",
  noReleasesBefore: "Brak premier — zaimportuj listę (",
  noReleasesAfter: ").",
  bestOfTitle: "Best of {year}",
  bestOfAll: "całość →",
  nowPlaying: "Słuchasz teraz",
  nowPlayingFind: "poszukaj tego w portalu →",
  yours: "Twoje",
  manageProfile: "profil i preferencje →",
  recentComments: "Ostatnie komentarze",
};
type T = typeof pl;

const en: T = {
  lineupTitle: "Lineup changes",
  lineupNote: "From MusicBrainz membership dates — the last year and a half. ★ marks your favourite bands.",
  lineupEmpty: "You have no favourite bands yet. Star any band on its page and you'll see here who joined it and who left.",
  lineupNoNews: "Nothing has changed lately in your favourite bands — at least nothing that made it into MusicBrainz.",
  joined: "joined",
  left: "left",
  lineupLoading: "Checking for lineup changes…",
  heroTitle: "A journey through music",
  heroTextBefore: "Your journey with music starts here. Dive into this wonderful world, travel through it ",
  heroTextBold: "by visiting artists and following where they went next",
  heroTextAfter: ". Welcome aboard.",
  loginCta: "Sign in",
  loginPromptRest: " to set your preferences, rate and comment.",
  releasesForYou: "New releases for you",
  releasesThisWeek: "New releases this week",
  allReleases: "all →",
  noReleasesBefore: "No releases yet — import the list (",
  noReleasesAfter: ").",
  bestOfTitle: "Best of {year}",
  bestOfAll: "see all →",
  nowPlaying: "Now playing",
  nowPlayingFind: "find this in the portal →",
  yours: "Yours",
  manageProfile: "profile and preferences →",
  recentComments: "Recent comments",
};

const es: T = {
  lineupTitle: "Cambios de formación",
  lineupNote: "Según las fechas de pertenencia en MusicBrainz — el último año y medio. ★ marca tus bandas favoritas.",
  lineupEmpty: "Todavía no tienes bandas favoritas. Marca cualquier banda con una estrella en su página y aquí verás quién entró y quién se fue.",
  lineupNoNews: "Últimamente no ha cambiado nada en tus bandas favoritas — al menos nada que haya llegado a MusicBrainz.",
  joined: "se unió a",
  left: "dejó",
  lineupLoading: "Comprobando cambios de formación…",
  heroTitle: "Un viaje por la música",
  heroTextBefore: "Tu viaje con la música empieza aquí. Sumérgete en este mundo estupendo, recórrelo ",
  heroTextBold: "visitando artistas y siguiendo sus siguientes pasos",
  heroTextAfter: ". Te esperamos.",
  loginCta: "Inicia sesión",
  loginPromptRest: " para configurar tus preferencias, valorar y comentar.",
  releasesForYou: "Novedades para ti",
  releasesThisWeek: "Novedades de la semana",
  allReleases: "todas →",
  noReleasesBefore: "Todavía no hay novedades — importa la lista (",
  noReleasesAfter: ").",
  bestOfTitle: "Lo mejor de {year}",
  bestOfAll: "ver todo →",
  nowPlaying: "Sonando ahora",
  nowPlayingFind: "búscalo en el portal →",
  yours: "Lo tuyo",
  manageProfile: "perfil y preferencias →",
  recentComments: "Comentarios recientes",
};

const de: T = {
  lineupTitle: "Besetzungswechsel",
  lineupNote: "Aus den Mitgliedschaftsdaten von MusicBrainz — die letzten anderthalb Jahre. ★ markiert deine Lieblingsbands.",
  lineupEmpty: "Du hast noch keine Lieblingsbands. Setz auf einer Bandseite einen Stern, dann siehst du hier, wer dazugekommen und wer gegangen ist.",
  lineupNoNews: "In deinen Lieblingsbands hat sich zuletzt nichts geändert — jedenfalls nichts, was in MusicBrainz gelandet ist.",
  joined: "wechselte zu",
  left: "verließ",
  lineupLoading: "Prüfe Besetzungswechsel…",
  heroTitle: "Eine Reise durch die Musik",
  heroTextBefore: "Deine Reise mit der Musik beginnt hier. Tauch ein in diese wunderbare Welt, reise durch sie, ",
  heroTextBold: "indem du Künstler besuchst und ihren nächsten Schritten folgst",
  heroTextAfter: ". Willkommen an Bord.",
  loginCta: "Anmelden",
  loginPromptRest: ", um deine Einstellungen festzulegen, zu bewerten und zu kommentieren.",
  releasesForYou: "Neuerscheinungen für dich",
  releasesThisWeek: "Neuerscheinungen der Woche",
  allReleases: "alle →",
  noReleasesBefore: "Noch keine Neuerscheinungen — importiere die Liste (",
  noReleasesAfter: ").",
  bestOfTitle: "Best of {year}",
  bestOfAll: "alles ansehen →",
  nowPlaying: "Läuft gerade",
  nowPlayingFind: "im Portal danach suchen →",
  yours: "Deins",
  manageProfile: "Profil und Einstellungen →",
  recentComments: "Neueste Kommentare",
};

export const home: Record<Locale, T> = { pl, en, es, de };
