/**
 * Napisy ekranu: lists. Polski jest źródłem prawdy — z niego bierzemy typ.
 *
 * Obejmuje /podroze ORAZ /best-of — best-of nie ma osobnego pliku słownika,
 * bo to blisko spokrewnione zestawienia (obie strony pokazują to samo: rangi
 * płyt i artystów, tylko z innych źródeł danych).
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  meLabel: "sobie (do posłuchania)",
  visitedMark: "znam",
  visitedNote: "Odhacza się samo: gdy ocenisz płytę albo wyjdziesz stąd do Spotify czy Tidala. Ptaszek możesz też postawić ręcznie.",
  visitedCount: "poznane: {done} z {all}",
  markVisited: "odhacz",
  unmarkVisited: "cofnij",
  openIn: "posłuchaj w {name}",
  onlySearch: "{name}: nie mam bezpośredniego adresu — otworzy się wyszukiwanie",
  notChecked: "{name}: jeszcze nie sprawdzone — może otworzyć wyszukiwanie",
  toSpotify: "Wyślij do Spotify",
  toSpotifyNote: "Powstanie prywatna playlista z płyt tej podróży. Zespoły i koncerty zostaną pominięte — playlista to utwory.",
  spotifyConnect: "Połącz ze Spotify",
  fromSpotifyTitle: "Ze Spotify",
  fromSpotifyIntro: "Płyty wyciągnięte z playlisty w Spotify. Utwory zostały tam — tu są albumy, po jednym wpisie na płytę.",
  fromSpotifySkipped: "Nie udało się dowiązać {n} płyt — puść ściąganie jeszcze raz, dowiąże kolejne.",
  spotifyImport: "Ściągnij listy ze Spotify",
  spotifyImportNote: "Twoje playlisty ze Spotify. Z każdej robi się podróż — nie utwór po utworze, tylko płyty, z których te utwory są.",
  spotifyImportEmpty: "Nie widzę żadnej playlisty. Albo ich nie ma, albo konto podłączyłeś, zanim portal zaczął prosić o zgodę na ich odczyt — wtedy połącz je od nowa.",
  spotifyImportReconnect: "Połącz Spotify od nowa",
  spotifyImportGrab: "zrób z tego podróż",
  spotifyImportTracks: "{n} utw.",
  tidalImport: "Ściągnij listy z Tidala",
  tidalImportNote: "Twoje playlisty z Tidala. Z każdej robi się podróż — nie utwór po utworze, tylko płyty, z których te utwory są.",
  tidalImportEmpty: "Nie widzę żadnej playlisty. Albo ich nie ma, albo Tidal nie dopuścił jeszcze tej aplikacji do odczytu — wtedy połącz konto od nowa za jakiś czas.",
  tidalConnect: "Połącz z Tidalem",
  tidalDisconnect: "Odłącz Tidala",
  tidalConnected: "Konto Tidala połączone.",
  tidalNote: "Dobrowolne i tylko do odczytu: portal widzi wyłącznie Twoje playlisty i nic w Tidalu nie zmienia.",
  fromTidalTitle: "Z Tidala",
  fromTidalIntro: "Płyty wyciągnięte z playlisty w Tidalu. Utwory zostały tam — tu są albumy, po jednym wpisie na płytę.",
  playedTitle: "Co grałem",
  playedIntro: "Co puściłeś stąd — z portalu w Spotify albo w Tidala. Osobno, niżej, to co portal podejrzał w Spotify. Nikt inny tego nie widzi.",
  playedEmpty: "Jeszcze nic. Zacznie się zapełniać, gdy wyjdziesz stąd w Spotify albo Tidala.",
  playedPortal: "Puszczone z portalu",
  playedSpotify: "A to leciało w Spotify",
  playedSpotifyNote: "Nie z portalu — sam zbiór, dla kontekstu.",
  playedAgain: "Zrób z tego podróż",
  playedAgainNote: "Ostatnie płyty z dziennika trafią na nową listę — do odhaczania i do wysłania jako playlista.",
  playedSimilar: "Poszukaj czegoś podobnego",
  playedLiked: "Poszukaj pod to, co lubię",
  playedTop: "Ostatnio siedzisz w tym",
  playedFrom: "z portalu",
  playedPrompt: "Ostatnio słucham: {kto}. Poszukaj czegoś w tym klimacie, ale nie tych samych zespołów. Przy każdej propozycji napisz, co ją z tym łączy.",
  playedSince: "odsłuchań",
  laterTitle: "Do posłuchania",
  laterAdd: "Do posłuchania",
  laterOn: "W kolejce",
  laterRemove: "Zdejmij z kolejki",
  laterIntro: "Rzeczy odłożone na później — jednym kliknięciem tam i z powrotem.",
  laterEmpty: "Pusto. Odkładaj tu wszystko, czego nie chcesz zgubić, a nie masz teraz czasu posłuchać.",
  spotifyOk: "Playlista gotowa: {n} utworów.",
  spotifySkipped: "Pominięto przystanków: {n}.",
  spotifyOpen: "otwórz w Spotify →",
  spotifyEmpty: "Nie udało się dopasować żadnej płyty — playlista nie powstała.",
  spotifyError: "Spotify odmówił. Sprawdź połączenie konta w profilu.",
  journalTitle: "Dziennik podróży",
  journalNote: "Twoje ślady w portalu — od najnowszego.",
  journalEmpty: "Dziennik jest jeszcze pusty. Polub płytę, oceń artystę albo dopisz pierwszy przystanek — zapisze się tutaj.",
  journalAll: "cały dziennik",
  journalToday: "dziś",
  journalYesterday: "wczoraj",
  jStop: "przystanek w",
  jJourney: "wytyczona podróż",
  jAlbumLike: "polubiona płyta",
  jAlbumDislike: "odrzucona płyta",
  jArtistLike: "artysta do ulubionych",
  jArtistDislike: "artysta odrzucony",
  jRating: "ocena {score}/10",
  jComment: "komentarz",
  jShared: "polecone przez {name}",
  myListsTitle: "Twoje podróże",
  myListsIntro: "Ułożona przez Ciebie trasa przez muzykę: płyty, artyści, muzycy, koncerty — w jednej podróży. Możesz ją komuś polecić.",
  newListTitle: "Nowa podróż",
  newListPlaceholder: "np. Death metal dla początkujących",
  newListDescription: "Dokąd prowadzi ta podróż? (nieobowiązkowe)",
  createList: "Wytycz podróż",
  noMyLists: "Nie masz jeszcze żadnej podróży.",
  itemsCount: { one: "{n} przystanek", few: "{n} przystanki", many: "{n} przystanków" } as { one: string; few?: string; many: string },
  emptyMyList: "Pusta podróż — jeszcze bez przystanków. Dodaj pierwszy przyciskiem „Do podróży” na stronie płyty albo artysty.",
  sharedWithMeTitle: "Polecone Tobie",
  sharedBy: "poleca {name}",
  hideShare: "schowaj",
  noSharedWithMe: "Nikt Ci jeszcze niczego nie polecił.",
  shareTitle: "Poleć tę podróż",
  shareNote: "Dopisz słowo od siebie (nieobowiązkowe)",
  shareSubmit: "Poleć",
  shareSearch: "Szukaj",
  shareSearchPlaceholder: "nazwa osoby, której chcesz polecić",
  shareNobodyFound: "Nikt taki się nie zgodził na polecanie — albo nazwa jest inna.",
  shareNote2: "Znajdziesz tu tylko tych, którzy w swoim profilu na to pozwolili.",
  shareNoUsers: "Nie ma komu polecić — jesteś na razie jedyną osobą w portalu.",
  sharedAlready: "Już polecone: {names}",
  pickStops: "Wybierz przystanki",
  pickStopsNote: "Zrobi z płyt tej podróży nową listę: po dwa kawałki z każdej, wybrane z prawdziwej tracklisty. Ta podróż zostaje bez zmian.",
  trackLabel: "Utwór",
  deleteList: "Usuń podróż",
  deleteConfirm: "Na pewno usunąć „{title}”? Tego się nie cofnie.",
  deleteYes: "Tak, usuń",
  removeItem: "usuń przystanek",
  listBy: "podróż użytkownika {name}",
  tryAgain: "To nie to? Popraw opis i ułóż od nowa →",
  addTo: "Do podróży",
  pickList: "Dopisz do istniejącej podróży",
  orNewList: "albo wytycz nową",
  addToSubmit: "Dodaj",
  onLists: "Już w podróżach",
  emptyList: "Jeszcze pusto — bądź pierwszy.",
  bannerTitle: "Podróże",
  bannerIntro: "Stałe: ",
  weeklyReleasesLink: "premiery piątkowe",
  bannerConnected: " ({n} połączonych z MusicBrainz) i ",
  bestOfLink: "best of roku",
  bannerOutro: ". Poniżej podróże i zestawienia społeczności portalu.",
  titleTopAlbums: "Najwyżej oceniane płyty",
  titleTopArtists: "Najwyżej oceniani artyści",
  titleMostLiked: "Najbardziej lubiane płyty",
  titleMostFav: "Najczęściej w ulubionych",
  titleMostCommentedAlbums: "Najbardziej komentowane płyty",
  titleMostCommentedArtists: "Najbardziej komentowani artyści",
  commentsCount: "{n} kom.",
  myAlbums: "Moje płyty",
  myArtists: "Moi artyści",
  manage: "zarządzaj →",
  noBestOf: "Brak danych Best of. Uruchom ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Rok",
  categoriesLabel: "Kategorie",
  numberOne: "Numer 1",
  ratingsLabel: "Oceny",
};
type T = typeof pl;

const en: T = {
  meLabel: "myself (to listen to)",
  visitedMark: "known",
  visitedNote: "It ticks itself: when you rate an album, or leave from here to Spotify or Tidal. You can also tick it by hand.",
  visitedCount: "known: {done} of {all}",
  markVisited: "tick",
  unmarkVisited: "undo",
  openIn: "listen on {name}",
  onlySearch: "{name}: no direct address — this opens a search",
  notChecked: "{name}: not checked yet — may open a search",
  toSpotify: "Send to Spotify",
  toSpotifyNote: "A private playlist from this journey's albums. Bands and concerts are left out — a playlist is tracks.",
  spotifyConnect: "Connect Spotify",
  fromSpotifyTitle: "From Spotify",
  fromSpotifyIntro: "Albums pulled out of a Spotify playlist. The tracks stayed there — here are the records, one entry per album.",
  fromSpotifySkipped: "Could not match {n} albums — run the import again and it will pick up more.",
  spotifyImport: "Import your Spotify playlists",
  spotifyImportNote: "Your Spotify playlists. Each becomes a journey — not track by track, but the albums those tracks come from.",
  spotifyImportEmpty: "No playlists here. Either there are none, or you connected the account before the portal started asking permission to read them — reconnect it in that case.",
  spotifyImportReconnect: "Reconnect Spotify",
  spotifyImportGrab: "turn into a journey",
  spotifyImportTracks: "{n} tracks",
  tidalImport: "Import your TIDAL playlists",
  tidalImportNote: "Your TIDAL playlists. Each becomes a journey — not track by track, but the albums those tracks come from.",
  tidalImportEmpty: "No playlists here. Either there are none, or TIDAL has not cleared this app for reading them yet — in that case reconnect the account later.",
  tidalConnect: "Connect TIDAL",
  tidalDisconnect: "Disconnect TIDAL",
  tidalConnected: "TIDAL account connected.",
  tidalNote: "Optional and read-only: the portal sees your playlists and changes nothing in TIDAL.",
  fromTidalTitle: "From TIDAL",
  fromTidalIntro: "Albums pulled out of a TIDAL playlist. The tracks stayed there — here are the records, one entry per album.",
  playedTitle: "What I played",
  playedIntro: "What you played from here — into Spotify or Tidal. Separately, below, what the portal saw on Spotify. Nobody else sees this.",
  playedEmpty: "Nothing yet. It fills up once you leave here for Spotify or Tidal.",
  playedPortal: "Played from the portal",
  playedSpotify: "And this was on in Spotify",
  playedSpotifyNote: "Not from the portal — a separate set, for context.",
  playedAgain: "Turn this into a journey",
  playedAgainNote: "Recent albums from the log go onto a new list — to tick off and to send as a playlist.",
  playedSimilar: "Find something similar",
  playedLiked: "Find something for what I like",
  playedTop: "Lately you're deep in",
  playedFrom: "from the portal",
  playedPrompt: "Lately I've been listening to: {kto}. Find something in that vein, but not those same bands. For each suggestion say what connects it.",
  playedSince: "plays",
  laterTitle: "To listen to",
  laterAdd: "Listen later",
  laterOn: "Queued",
  laterRemove: "Take out of the queue",
  laterIntro: "Things put aside for later — one click each way.",
  laterEmpty: "Empty. Put here whatever you don't want to lose track of but have no time for right now.",
  spotifyOk: "Playlist ready: {n} tracks.",
  spotifySkipped: "Stops left out: {n}.",
  spotifyOpen: "open in Spotify →",
  spotifyEmpty: "No album could be matched — no playlist was created.",
  spotifyError: "Spotify refused. Check the account connection in your profile.",
  journalTitle: "Travel journal",
  journalNote: "Your tracks across the portal — newest first.",
  journalEmpty: "The journal is still empty. Like an album, rate a band or add a first stop — it lands here.",
  journalAll: "full journal",
  journalToday: "today",
  journalYesterday: "yesterday",
  jStop: "stop on",
  jJourney: "journey plotted",
  jAlbumLike: "album liked",
  jAlbumDislike: "album passed on",
  jArtistLike: "band favourited",
  jArtistDislike: "band passed on",
  jRating: "rated {score}/10",
  jComment: "comment",
  jShared: "recommended by {name}",
  myListsTitle: "Your journeys",
  myListsIntro: "A route through music you plotted yourself: albums, bands, musicians, concerts — in one journey. You can recommend it to someone.",
  newListTitle: "New journey",
  newListPlaceholder: "e.g. Death metal for beginners",
  newListDescription: "Where does this journey lead? (optional)",
  createList: "Plot a journey",
  noMyLists: "You don't have any journeys yet.",
  itemsCount: { one: "{n} stop", many: "{n} stops" },
  emptyMyList: "An empty journey — no stops yet. Add the first one with the “Add to journey” button on an album or band page.",
  sharedWithMeTitle: "Recommended to you",
  sharedBy: "from {name}",
  hideShare: "hide",
  noSharedWithMe: "Nobody has recommended you anything yet.",
  shareTitle: "Recommend this journey",
  shareNote: "Add a word of your own (optional)",
  shareSubmit: "Recommend",
  shareSearch: "Search",
  shareSearchPlaceholder: "name of the person you want to send it to",
  shareNobodyFound: "Nobody by that name has allowed recommendations — or the name is different.",
  shareNote2: "You will only find people who allowed this in their profile.",
  shareNoUsers: "Nobody to recommend it to — you're the only person here so far.",
  sharedAlready: "Already sent to: {names}",
  pickStops: "Pick the stops",
  pickStopsNote: "Turns this journey's albums into a new list: two tracks from each, chosen from the real tracklist. This journey stays as it is.",
  trackLabel: "Track",
  deleteList: "Delete journey",
  deleteConfirm: "Really delete “{title}”? This can't be undone.",
  deleteYes: "Yes, delete",
  removeItem: "remove stop",
  listBy: "a journey by {name}",
  tryAgain: "Not it? Tweak the description and rebuild →",
  addTo: "Add to journey",
  pickList: "Add to an existing journey",
  orNewList: "or plot a new one",
  addToSubmit: "Add",
  onLists: "Already on journeys",
  emptyList: "Still empty — be the first.",
  bannerTitle: "Journeys",
  bannerIntro: "Regulars: ",
  weeklyReleasesLink: "Friday releases",
  bannerConnected: " ({n} linked to MusicBrainz) and ",
  bestOfLink: "best of the year",
  bannerOutro: ". Below are the portal community's own lists.",
  titleTopAlbums: "Top-rated albums",
  titleTopArtists: "Top-rated artists",
  titleMostLiked: "Most-liked albums",
  titleMostFav: "Most favourited artists",
  titleMostCommentedAlbums: "Most-commented albums",
  titleMostCommentedArtists: "Most-commented artists",
  commentsCount: "{n} comments",
  myAlbums: "My albums",
  myArtists: "My artists",
  manage: "manage →",
  noBestOf: "No Best of data yet. Run ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Year",
  categoriesLabel: "Categories",
  numberOne: "Number 1",
  ratingsLabel: "Scores",
};

const es: T = {
  meLabel: "a mí (para escuchar)",
  visitedMark: "conocido",
  visitedNote: "Se marca solo: cuando puntúas un disco o sales de aquí a Spotify o Tidal. También puedes marcarlo a mano.",
  visitedCount: "conocidos: {done} de {all}",
  markVisited: "marcar",
  unmarkVisited: "deshacer",
  openIn: "escuchar en {name}",
  onlySearch: "{name}: no tengo dirección directa; se abrirá una búsqueda",
  notChecked: "{name}: aún sin comprobar; puede abrir una búsqueda",
  toSpotify: "Enviar a Spotify",
  toSpotifyNote: "Una lista privada con los discos de este viaje. Las bandas y los conciertos quedan fuera: una lista son canciones.",
  spotifyConnect: "Conectar Spotify",
  fromSpotifyTitle: "De Spotify",
  fromSpotifyIntro: "Discos sacados de una lista de Spotify. Las canciones se quedaron allí — aquí están los álbumes, una entrada por disco.",
  fromSpotifySkipped: "No se pudieron enlazar {n} discos — repite la importación y enlazará más.",
  spotifyImport: "Traer tus listas de Spotify",
  spotifyImportNote: "Tus listas de Spotify. Cada una se convierte en un viaje — no canción por canción, sino los discos de los que salen.",
  spotifyImportEmpty: "No veo ninguna lista. O no hay, o conectaste la cuenta antes de que el portal pidiera permiso para leerlas — en ese caso vuelve a conectarla.",
  spotifyImportReconnect: "Volver a conectar Spotify",
  spotifyImportGrab: "hacer un viaje con esto",
  spotifyImportTracks: "{n} canc.",
  tidalImport: "Traer tus listas de TIDAL",
  tidalImportNote: "Tus listas de TIDAL. Cada una se convierte en un viaje — no canción por canción, sino los discos de los que salen.",
  tidalImportEmpty: "No veo ninguna lista. O no hay, o TIDAL aún no ha autorizado a esta aplicación a leerlas — en ese caso vuelve a conectar la cuenta más tarde.",
  tidalConnect: "Conectar TIDAL",
  tidalDisconnect: "Desconectar TIDAL",
  tidalConnected: "Cuenta de TIDAL conectada.",
  tidalNote: "Opcional y solo de lectura: el portal ve tus listas y no cambia nada en TIDAL.",
  fromTidalTitle: "De TIDAL",
  fromTidalIntro: "Discos sacados de una lista de TIDAL. Las canciones se quedaron allí — aquí están los álbumes, una entrada por disco.",
  playedTitle: "Lo que sonó",
  playedIntro: "Lo que pusiste desde aquí — a Spotify o Tidal. Aparte, más abajo, lo que el portal vio en Spotify. Nadie más lo ve.",
  playedEmpty: "Nada aún. Se irá llenando cuando salgas de aquí a Spotify o Tidal.",
  playedPortal: "Puesto desde el portal",
  playedSpotify: "Y esto sonaba en Spotify",
  playedSpotifyNote: "No desde el portal — otro conjunto, como contexto.",
  playedAgain: "Convertirlo en un viaje",
  playedAgainNote: "Los discos recientes del diario pasan a una lista nueva — para tachar y para enviar como lista de reproducción.",
  playedSimilar: "Busca algo parecido",
  playedLiked: "Busca según lo que me gusta",
  playedTop: "Últimamente estás metido en",
  playedFrom: "desde el portal",
  playedPrompt: "Últimamente escucho: {kto}. Busca algo en esa línea, pero no los mismos grupos. En cada propuesta di qué los une.",
  playedSince: "escuchas",
  laterTitle: "Para escuchar",
  laterAdd: "Escuchar luego",
  laterOn: "En la cola",
  laterRemove: "Quitar de la cola",
  laterIntro: "Cosas apartadas para después — a un clic en cada sentido.",
  laterEmpty: "Vacío. Guarda aquí lo que no quieras perder de vista pero no tengas tiempo de escuchar ahora.",
  spotifyOk: "Lista lista: {n} canciones.",
  spotifySkipped: "Paradas omitidas: {n}.",
  spotifyOpen: "abrir en Spotify →",
  spotifyEmpty: "No se pudo encontrar ningún disco: no se creó la lista.",
  spotifyError: "Spotify se negó. Revisa la conexión de la cuenta en tu perfil.",
  journalTitle: "Diario de viaje",
  journalNote: "Tus huellas en el portal — de lo más reciente.",
  journalEmpty: "El diario aún está vacío. Marca un disco, puntúa una banda o añade una primera parada: aparecerá aquí.",
  journalAll: "diario completo",
  journalToday: "hoy",
  journalYesterday: "ayer",
  jStop: "parada en",
  jJourney: "viaje trazado",
  jAlbumLike: "disco marcado",
  jAlbumDislike: "disco descartado",
  jArtistLike: "banda a favoritos",
  jArtistDislike: "banda descartada",
  jRating: "puntuado {score}/10",
  jComment: "comentario",
  jShared: "recomendado por {name}",
  myListsTitle: "Tus viajes",
  myListsIntro: "Una ruta por la música trazada por ti: discos, bandas, músicos, conciertos — en un solo viaje. Puedes recomendárselo a alguien.",
  newListTitle: "Nuevo viaje",
  newListPlaceholder: "p. ej. Death metal para empezar",
  newListDescription: "¿Adónde lleva este viaje? (opcional)",
  createList: "Trazar el viaje",
  noMyLists: "Todavía no tienes ningún viaje.",
  itemsCount: { one: "{n} parada", many: "{n} paradas" },
  emptyMyList: "Viaje vacío — aún sin paradas. Añade la primera con el botón «Añadir al viaje» en la página de un disco o una banda.",
  sharedWithMeTitle: "Recomendado para ti",
  sharedBy: "de {name}",
  hideShare: "ocultar",
  noSharedWithMe: "Nadie te ha recomendado nada todavía.",
  shareTitle: "Recomendar este viaje",
  shareNote: "Añade unas palabras tuyas (opcional)",
  shareSubmit: "Recomendar",
  shareSearch: "Buscar",
  shareSearchPlaceholder: "nombre de la persona a la que quieres enviarlo",
  shareNobodyFound: "Nadie con ese nombre lo ha permitido, o el nombre es otro.",
  shareNote2: "Aquí solo aparecen quienes lo han permitido en su perfil.",
  shareNoUsers: "No hay a quién recomendársela — por ahora eres la única persona aquí.",
  sharedAlready: "Ya enviada a: {names}",
  pickStops: "Elegir las paradas",
  pickStopsNote: "Convierte los discos de este viaje en una lista nueva: dos temas de cada uno, elegidos de la lista real de pistas. Este viaje no cambia.",
  trackLabel: "Tema",
  deleteList: "Borrar viaje",
  deleteConfirm: "¿Seguro que quieres borrar «{title}»? No se puede deshacer.",
  deleteYes: "Sí, borrar",
  removeItem: "quitar parada",
  listBy: "un viaje de {name}",
  tryAgain: "¿No es esto? Ajusta la descripción y rehazlo →",
  addTo: "Añadir al viaje",
  pickList: "Añadir a un viaje existente",
  orNewList: "o trazar uno nuevo",
  addToSubmit: "Añadir",
  onLists: "Ya está en viajes",
  emptyList: "Todavía vacío — sé el primero.",
  bannerTitle: "Viajes",
  bannerIntro: "Fijas: ",
  weeklyReleasesLink: "novedades de los viernes",
  bannerConnected: " ({n} enlazadas con MusicBrainz) y ",
  bestOfLink: "lo mejor del año",
  bannerOutro: ". Debajo, las listas de la comunidad del portal.",
  titleTopAlbums: "Discos mejor valorados",
  titleTopArtists: "Artistas mejor valorados",
  titleMostLiked: "Discos más marcados como favoritos",
  titleMostFav: "Artistas más marcados como favoritos",
  titleMostCommentedAlbums: "Discos más comentados",
  titleMostCommentedArtists: "Artistas más comentados",
  commentsCount: "{n} com.",
  myAlbums: "Mis discos",
  myArtists: "Mis artistas",
  manage: "gestionar →",
  noBestOf: "Todavía no hay datos de Best of. Ejecuta ",
  noBestOfAfter: ".",
  bestOfYear: "Lo mejor de {year}",
  yearLabel: "Año",
  categoriesLabel: "Categorías",
  numberOne: "Número 1",
  ratingsLabel: "Puntuaciones",
};

const de: T = {
  meLabel: "mir selbst (zum Anhören)",
  visitedMark: "bekannt",
  visitedNote: "Hakt sich von selbst ab: wenn du ein Album bewertest oder von hier zu Spotify oder Tidal gehst. Von Hand geht es auch.",
  visitedCount: "bekannt: {done} von {all}",
  markVisited: "abhaken",
  unmarkVisited: "zurück",
  openIn: "hören auf {name}",
  onlySearch: "{name}: keine direkte Adresse — es öffnet sich eine Suche",
  notChecked: "{name}: noch nicht geprüft — öffnet eventuell eine Suche",
  toSpotify: "An Spotify senden",
  toSpotifyNote: "Eine private Playlist aus den Alben dieser Reise. Bands und Konzerte bleiben draußen — eine Playlist besteht aus Titeln.",
  spotifyConnect: "Spotify verbinden",
  fromSpotifyTitle: "Aus Spotify",
  fromSpotifyIntro: "Alben aus einer Spotify-Playlist herausgezogen. Die Titel sind dort geblieben — hier stehen die Platten, ein Eintrag pro Album.",
  fromSpotifySkipped: "{n} Alben ließen sich nicht zuordnen — starte den Import noch einmal, dann kommen weitere dazu.",
  spotifyImport: "Spotify-Playlists holen",
  spotifyImportNote: "Deine Playlists aus Spotify. Aus jeder wird eine Reise — nicht Titel für Titel, sondern die Platten, von denen die Titel stammen.",
  spotifyImportEmpty: "Keine Playlist zu sehen. Entweder gibt es keine, oder du hast das Konto verbunden, bevor das Portal um Leserechte dafür gebeten hat — dann verbinde es neu.",
  spotifyImportReconnect: "Spotify neu verbinden",
  spotifyImportGrab: "Reise daraus machen",
  spotifyImportTracks: "{n} Titel",
  tidalImport: "TIDAL-Playlists holen",
  tidalImportNote: "Deine Playlists aus TIDAL. Aus jeder wird eine Reise — nicht Titel für Titel, sondern die Platten, von denen die Titel stammen.",
  tidalImportEmpty: "Keine Playlist zu sehen. Entweder gibt es keine, oder TIDAL hat diese App noch nicht zum Lesen freigegeben — dann verbinde das Konto später neu.",
  tidalConnect: "TIDAL verbinden",
  tidalDisconnect: "TIDAL trennen",
  tidalConnected: "TIDAL-Konto verbunden.",
  tidalNote: "Freiwillig und nur lesend: Das Portal sieht deine Playlists und ändert nichts in TIDAL.",
  fromTidalTitle: "Aus TIDAL",
  fromTidalIntro: "Alben aus einer TIDAL-Playlist herausgezogen. Die Titel sind dort geblieben — hier stehen die Platten, ein Eintrag pro Album.",
  playedTitle: "Was lief",
  playedIntro: "Was du von hier aus gestartet hast — zu Spotify oder Tidal. Getrennt davon, weiter unten, was das Portal bei Spotify gesehen hat. Sonst sieht das niemand.",
  playedEmpty: "Noch nichts. Es füllt sich, sobald du von hier zu Spotify oder Tidal springst.",
  playedPortal: "Vom Portal aus gestartet",
  playedSpotify: "Und das lief bei Spotify",
  playedSpotifyNote: "Nicht vom Portal — ein eigener Satz, als Kontext.",
  playedAgain: "Daraus eine Reise machen",
  playedAgainNote: "Die letzten Alben aus dem Journal kommen auf eine neue Liste — zum Abhaken und zum Senden als Playlist.",
  playedSimilar: "Etwas Ähnliches suchen",
  playedLiked: "Nach dem suchen, was ich mag",
  playedTop: "Zuletzt steckst du in",
  playedFrom: "aus dem Portal",
  playedPrompt: "Zuletzt höre ich: {kto}. Such etwas in dieser Richtung, aber nicht dieselben Bands. Sag bei jedem Vorschlag, was ihn damit verbindet.",
  playedSince: "Durchläufe",
  laterTitle: "Zum Hören",
  laterAdd: "Später hören",
  laterOn: "In der Warteschlange",
  laterRemove: "Aus der Warteschlange nehmen",
  laterIntro: "Zurückgelegtes für später — ein Klick hin, ein Klick zurück.",
  laterEmpty: "Leer. Leg hier alles ab, was du nicht verlieren willst, wofür jetzt aber keine Zeit ist.",
  spotifyOk: "Playlist fertig: {n} Titel.",
  spotifySkipped: "Ausgelassene Halte: {n}.",
  spotifyOpen: "in Spotify öffnen →",
  spotifyEmpty: "Kein Album gefunden — es wurde keine Playlist erstellt.",
  spotifyError: "Spotify hat abgelehnt. Prüfe die Kontoverbindung im Profil.",
  journalTitle: "Reisetagebuch",
  journalNote: "Deine Spuren im Portal — das Neueste zuerst.",
  journalEmpty: "Das Tagebuch ist noch leer. Markiere ein Album, bewerte eine Band oder setze einen ersten Halt — es landet hier.",
  journalAll: "ganzes Tagebuch",
  journalToday: "heute",
  journalYesterday: "gestern",
  jStop: "Halt in",
  jJourney: "Reise abgesteckt",
  jAlbumLike: "Album gemerkt",
  jAlbumDislike: "Album abgelehnt",
  jArtistLike: "Band zu Favoriten",
  jArtistDislike: "Band abgelehnt",
  jRating: "bewertet {score}/10",
  jComment: "Kommentar",
  jShared: "empfohlen von {name}",
  myListsTitle: "Deine Reisen",
  myListsIntro: "Eine von dir gelegte Route durch die Musik: Alben, Bands, Musiker, Konzerte — in einer Reise. Du kannst sie jemandem empfehlen.",
  newListTitle: "Neue Reise",
  newListPlaceholder: "z. B. Death Metal für Einsteiger",
  newListDescription: "Wohin führt diese Reise? (optional)",
  createList: "Reise anlegen",
  noMyLists: "Du hast noch keine Reise.",
  itemsCount: { one: "{n} Station", many: "{n} Stationen" },
  emptyMyList: "Leere Reise — noch ohne Stationen. Füge die erste über den Knopf „Zur Reise“ auf einer Album- oder Bandseite hinzu.",
  sharedWithMeTitle: "Für dich empfohlen",
  sharedBy: "von {name}",
  hideShare: "ausblenden",
  noSharedWithMe: "Dir hat noch niemand etwas empfohlen.",
  shareTitle: "Diese Reise empfehlen",
  shareNote: "Schreib ein paar eigene Worte dazu (optional)",
  shareSubmit: "Empfehlen",
  shareSearch: "Suchen",
  shareSearchPlaceholder: "Name der Person, der du sie schicken willst",
  shareNobodyFound: "Niemand mit diesem Namen hat Empfehlungen erlaubt — oder der Name lautet anders.",
  shareNote2: "Hier findest du nur Leute, die es in ihrem Profil erlaubt haben.",
  shareNoUsers: "Niemand da, dem man sie empfehlen könnte — du bist bisher allein hier.",
  sharedAlready: "Schon geschickt an: {names}",
  pickStops: "Stationen auswählen",
  pickStopsNote: "Macht aus den Alben dieser Reise eine neue Liste: zwei Stücke von jedem, aus der echten Trackliste gewählt. Diese Reise bleibt, wie sie ist.",
  trackLabel: "Stück",
  deleteList: "Reise löschen",
  deleteConfirm: "„{title}” wirklich löschen? Das lässt sich nicht rückgängig machen.",
  deleteYes: "Ja, löschen",
  removeItem: "Station entfernen",
  listBy: "eine Reise von {name}",
  tryAgain: "Nicht das Richtige? Beschreibung anpassen und neu bauen →",
  addTo: "Zur Reise",
  pickList: "Zu einer vorhandenen Reise",
  orNewList: "oder eine neue anlegen",
  addToSubmit: "Hinzufügen",
  onLists: "Schon auf Reisen",
  emptyList: "Noch leer — sei der Erste.",
  bannerTitle: "Reisen",
  bannerIntro: "Fest: ",
  weeklyReleasesLink: "Freitagsneuerscheinungen",
  bannerConnected: " ({n} mit MusicBrainz verknüpft) und ",
  bestOfLink: "Best of des Jahres",
  bannerOutro: ". Darunter die Listen der Portal-Community.",
  titleTopAlbums: "Bestbewertete Alben",
  titleTopArtists: "Bestbewertete Künstler",
  titleMostLiked: "Meistgemochte Alben",
  titleMostFav: "Meiste Favoriten",
  titleMostCommentedAlbums: "Meistkommentierte Alben",
  titleMostCommentedArtists: "Meistkommentierte Künstler",
  commentsCount: "{n} Komm.",
  myAlbums: "Meine Alben",
  myArtists: "Meine Künstler",
  manage: "verwalten →",
  noBestOf: "Noch keine Best-of-Daten. Führe ",
  noBestOfAfter: " aus.",
  bestOfYear: "Best of {year}",
  yearLabel: "Jahr",
  categoriesLabel: "Kategorien",
  numberOne: "Nummer 1",
  ratingsLabel: "Wertungen",
};

export const lists: Record<Locale, T> = { pl, en, es, de };
