/**
 * Napisy ekranu: lists. Polski jest źródłem prawdy — z niego bierzemy typ.
 *
 * Obejmuje /listy ORAZ /best-of — best-of nie ma osobnego pliku słownika,
 * bo to blisko spokrewnione zestawienia (obie strony pokazują to samo: rangi
 * płyt i artystów, tylko z innych źródeł danych).
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  meLabel: "sobie (do posłuchania)",
  myListsTitle: "Twoje listy",
  myListsIntro: "Własne zestawienia: płyty, zespoły, muzycy — co chcesz, w jednej liście. Możesz je polecić innym.",
  newListTitle: "Nowa lista",
  newListPlaceholder: "np. Death metal dla początkujących",
  newListDescription: "O czym jest ta lista? (nieobowiązkowe)",
  createList: "Załóż listę",
  noMyLists: "Nie masz jeszcze żadnej listy.",
  itemsCount: { one: "{n} pozycja", few: "{n} pozycje", many: "{n} pozycji" } as { one: string; few?: string; many: string },
  emptyMyList: "Pusta lista. Dodaj coś przyciskiem „Do listy” na stronie płyty albo zespołu.",
  sharedWithMeTitle: "Polecone Tobie",
  sharedBy: "poleca {name}",
  hideShare: "schowaj",
  noSharedWithMe: "Nikt Ci jeszcze niczego nie polecił.",
  shareTitle: "Poleć tę listę",
  shareNote: "Dopisz słowo od siebie (nieobowiązkowe)",
  shareSubmit: "Poleć",
  shareNoUsers: "Nie ma komu polecić — jesteś na razie jedyną osobą w portalu.",
  sharedAlready: "Już polecone: {names}",
  deleteList: "Usuń listę",
  removeItem: "usuń",
  listBy: "lista użytkownika {name}",
  addTo: "Do listy",
  pickList: "Dopisz do istniejącej",
  orNewList: "albo załóż nową",
  addToSubmit: "Dodaj",
  onLists: "Już na listach",
  emptyList: "Jeszcze pusto — bądź pierwszy.",
  bannerTitle: "Listy",
  bannerIntro: "Stałe: ",
  weeklyReleasesLink: "premiery piątkowe",
  bannerConnected: " ({n} połączonych z MusicBrainz) i ",
  bestOfLink: "best of roku",
  bannerOutro: ". Poniżej listy społeczności portalu.",
  titleTopAlbums: "Najwyżej oceniane płyty",
  titleTopArtists: "Najwyżej oceniani artyści",
  titleMostLiked: "Najbardziej lubiane płyty",
  titleMostFav: "Najczęściej w ulubionych",
  titleMostCommentedAlbums: "Najbardziej komentowane płyty",
  titleMostCommentedArtists: "Najbardziej komentowani artyści",
  commentsCount: "{n} kom.",
  myAlbums: "Moje płyty",
  myArtists: "Moi artyści",
  manage: "zarządzaj →",
  noBestOf: "Brak danych Best of. Uruchom ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Rok",
  categoriesLabel: "Kategorie",
  numberOne: "Numer 1",
  ratingsLabel: "Oceny",
};
type T = typeof pl;

const en: T = {
  meLabel: "myself (to listen to)",
  myListsTitle: "Your lists",
  myListsIntro: "Your own line-ups: albums, bands, musicians — whatever you want, in one list. You can recommend them to other people.",
  newListTitle: "New list",
  newListPlaceholder: "e.g. Death metal for beginners",
  newListDescription: "What is this list about? (optional)",
  createList: "Create list",
  noMyLists: "You don't have any lists yet.",
  itemsCount: { one: "{n} item", many: "{n} items" },
  emptyMyList: "Empty list. Add something with the “Add to list” button on an album or band page.",
  sharedWithMeTitle: "Recommended to you",
  sharedBy: "from {name}",
  hideShare: "hide",
  noSharedWithMe: "Nobody has recommended you anything yet.",
  shareTitle: "Recommend this list",
  shareNote: "Add a word of your own (optional)",
  shareSubmit: "Recommend",
  shareNoUsers: "Nobody to recommend it to — you're the only person here so far.",
  sharedAlready: "Already sent to: {names}",
  deleteList: "Delete list",
  removeItem: "remove",
  listBy: "a list by {name}",
  addTo: "Add to list",
  pickList: "Add to an existing one",
  orNewList: "or start a new one",
  addToSubmit: "Add",
  onLists: "Already on",
  emptyList: "Still empty — be the first.",
  bannerTitle: "Lists",
  bannerIntro: "Regulars: ",
  weeklyReleasesLink: "Friday releases",
  bannerConnected: " ({n} linked to MusicBrainz) and ",
  bestOfLink: "best of the year",
  bannerOutro: ". Below are the portal community's own lists.",
  titleTopAlbums: "Top-rated albums",
  titleTopArtists: "Top-rated artists",
  titleMostLiked: "Most-liked albums",
  titleMostFav: "Most favourited artists",
  titleMostCommentedAlbums: "Most-commented albums",
  titleMostCommentedArtists: "Most-commented artists",
  commentsCount: "{n} comments",
  myAlbums: "My albums",
  myArtists: "My artists",
  manage: "manage →",
  noBestOf: "No Best of data yet. Run ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Year",
  categoriesLabel: "Categories",
  numberOne: "Number 1",
  ratingsLabel: "Scores",
};

const es: T = {
  meLabel: "a mí (para escuchar)",
  myListsTitle: "Tus listas",
  myListsIntro: "Tus propias selecciones: discos, bandas, músicos — lo que quieras, en una lista. Puedes recomendarlas a otras personas.",
  newListTitle: "Nueva lista",
  newListPlaceholder: "p. ej. Death metal para empezar",
  newListDescription: "¿De qué va esta lista? (opcional)",
  createList: "Crear lista",
  noMyLists: "Todavía no tienes ninguna lista.",
  itemsCount: { one: "{n} elemento", many: "{n} elementos" },
  emptyMyList: "Lista vacía. Añade algo con el botón «Añadir a lista» en la página de un disco o una banda.",
  sharedWithMeTitle: "Recomendado para ti",
  sharedBy: "de {name}",
  hideShare: "ocultar",
  noSharedWithMe: "Nadie te ha recomendado nada todavía.",
  shareTitle: "Recomendar esta lista",
  shareNote: "Añade unas palabras tuyas (opcional)",
  shareSubmit: "Recomendar",
  shareNoUsers: "No hay a quién recomendársela — por ahora eres la única persona aquí.",
  sharedAlready: "Ya enviada a: {names}",
  deleteList: "Borrar lista",
  removeItem: "quitar",
  listBy: "una lista de {name}",
  addTo: "Añadir a lista",
  pickList: "Añadir a una existente",
  orNewList: "o crear una nueva",
  addToSubmit: "Añadir",
  onLists: "Ya está en",
  emptyList: "Todavía vacío — sé el primero.",
  bannerTitle: "Listas",
  bannerIntro: "Fijas: ",
  weeklyReleasesLink: "novedades de los viernes",
  bannerConnected: " ({n} enlazadas con MusicBrainz) y ",
  bestOfLink: "lo mejor del año",
  bannerOutro: ". Debajo, las listas de la comunidad del portal.",
  titleTopAlbums: "Discos mejor valorados",
  titleTopArtists: "Artistas mejor valorados",
  titleMostLiked: "Discos más marcados como favoritos",
  titleMostFav: "Artistas más marcados como favoritos",
  titleMostCommentedAlbums: "Discos más comentados",
  titleMostCommentedArtists: "Artistas más comentados",
  commentsCount: "{n} com.",
  myAlbums: "Mis discos",
  myArtists: "Mis artistas",
  manage: "gestionar →",
  noBestOf: "Todavía no hay datos de Best of. Ejecuta ",
  noBestOfAfter: ".",
  bestOfYear: "Lo mejor de {year}",
  yearLabel: "Año",
  categoriesLabel: "Categorías",
  numberOne: "Número 1",
  ratingsLabel: "Puntuaciones",
};

const de: T = {
  meLabel: "mir selbst (zum Anhören)",
  myListsTitle: "Deine Listen",
  myListsIntro: "Eigene Zusammenstellungen: Alben, Bands, Musiker — was du willst, in einer Liste. Du kannst sie anderen empfehlen.",
  newListTitle: "Neue Liste",
  newListPlaceholder: "z. B. Death Metal für Einsteiger",
  newListDescription: "Worum geht es in dieser Liste? (optional)",
  createList: "Liste anlegen",
  noMyLists: "Du hast noch keine Liste.",
  itemsCount: { one: "{n} Eintrag", many: "{n} Einträge" },
  emptyMyList: "Leere Liste. Füge etwas über den Knopf „Zur Liste“ auf einer Album- oder Bandseite hinzu.",
  sharedWithMeTitle: "Für dich empfohlen",
  sharedBy: "von {name}",
  hideShare: "ausblenden",
  noSharedWithMe: "Dir hat noch niemand etwas empfohlen.",
  shareTitle: "Diese Liste empfehlen",
  shareNote: "Schreib ein paar eigene Worte dazu (optional)",
  shareSubmit: "Empfehlen",
  shareNoUsers: "Niemand da, dem man sie empfehlen könnte — du bist bisher allein hier.",
  sharedAlready: "Schon geschickt an: {names}",
  deleteList: "Liste löschen",
  removeItem: "entfernen",
  listBy: "eine Liste von {name}",
  addTo: "Zur Liste",
  pickList: "Zu einer vorhandenen hinzufügen",
  orNewList: "oder eine neue anlegen",
  addToSubmit: "Hinzufügen",
  onLists: "Schon auf",
  emptyList: "Noch leer — sei der Erste.",
  bannerTitle: "Listen",
  bannerIntro: "Fest: ",
  weeklyReleasesLink: "Freitagsneuerscheinungen",
  bannerConnected: " ({n} mit MusicBrainz verknüpft) und ",
  bestOfLink: "Best of des Jahres",
  bannerOutro: ". Darunter die Listen der Portal-Community.",
  titleTopAlbums: "Bestbewertete Alben",
  titleTopArtists: "Bestbewertete Künstler",
  titleMostLiked: "Meistgemochte Alben",
  titleMostFav: "Meiste Favoriten",
  titleMostCommentedAlbums: "Meistkommentierte Alben",
  titleMostCommentedArtists: "Meistkommentierte Künstler",
  commentsCount: "{n} Komm.",
  myAlbums: "Meine Alben",
  myArtists: "Meine Künstler",
  manage: "verwalten →",
  noBestOf: "Noch keine Best-of-Daten. Führe ",
  noBestOfAfter: " aus.",
  bestOfYear: "Best of {year}",
  yearLabel: "Jahr",
  categoriesLabel: "Kategorien",
  numberOne: "Nummer 1",
  ratingsLabel: "Wertungen",
};

export const lists: Record<Locale, T> = { pl, en, es, de };
