/**
 * Napisy ekranu: lists. Polski jest źródłem prawdy — z niego bierzemy typ.
 *
 * Obejmuje /listy ORAZ /best-of — best-of nie ma osobnego pliku słownika,
 * bo to blisko spokrewnione zestawienia (obie strony pokazują to samo: rangi
 * płyt i artystów, tylko z innych źródeł danych).
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  emptyList: "Jeszcze pusto — bądź pierwszy.",
  bannerTitle: "Listy",
  bannerIntro: "Stałe: ",
  weeklyReleasesLink: "premiery piątkowe",
  bannerConnected: " ({n} połączonych z MusicBrainz) i ",
  bestOfLink: "best of roku",
  bannerOutro: ". Poniżej listy społeczności portalu.",
  titleTopAlbums: "Najwyżej oceniane płyty",
  titleTopArtists: "Najwyżej oceniani artyści",
  titleMostLiked: "Najbardziej lubiane płyty",
  titleMostFav: "Najczęściej w ulubionych",
  titleMostCommentedAlbums: "Najbardziej komentowane płyty",
  titleMostCommentedArtists: "Najbardziej komentowani artyści",
  commentsCount: "{n} kom.",
  myAlbums: "Moje płyty",
  myArtists: "Moi artyści",
  manage: "zarządzaj →",
  noBestOf: "Brak danych Best of. Uruchom ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Rok",
  categoriesLabel: "Kategorie",
  numberOne: "Numer 1",
  ratingsLabel: "Oceny",
};
type T = typeof pl;

const en: T = {
  emptyList: "Still empty — be the first.",
  bannerTitle: "Lists",
  bannerIntro: "Regulars: ",
  weeklyReleasesLink: "Friday releases",
  bannerConnected: " ({n} linked to MusicBrainz) and ",
  bestOfLink: "best of the year",
  bannerOutro: ". Below are the portal community's own lists.",
  titleTopAlbums: "Top-rated albums",
  titleTopArtists: "Top-rated artists",
  titleMostLiked: "Most-liked albums",
  titleMostFav: "Most favourited artists",
  titleMostCommentedAlbums: "Most-commented albums",
  titleMostCommentedArtists: "Most-commented artists",
  commentsCount: "{n} comments",
  myAlbums: "My albums",
  myArtists: "My artists",
  manage: "manage →",
  noBestOf: "No Best of data yet. Run ",
  noBestOfAfter: ".",
  bestOfYear: "Best of {year}",
  yearLabel: "Year",
  categoriesLabel: "Categories",
  numberOne: "Number 1",
  ratingsLabel: "Scores",
};

const es: T = {
  emptyList: "Todavía vacío — sé el primero.",
  bannerTitle: "Listas",
  bannerIntro: "Fijas: ",
  weeklyReleasesLink: "novedades de los viernes",
  bannerConnected: " ({n} enlazadas con MusicBrainz) y ",
  bestOfLink: "lo mejor del año",
  bannerOutro: ". Debajo, las listas de la comunidad del portal.",
  titleTopAlbums: "Discos mejor valorados",
  titleTopArtists: "Artistas mejor valorados",
  titleMostLiked: "Discos más marcados como favoritos",
  titleMostFav: "Artistas más marcados como favoritos",
  titleMostCommentedAlbums: "Discos más comentados",
  titleMostCommentedArtists: "Artistas más comentados",
  commentsCount: "{n} com.",
  myAlbums: "Mis discos",
  myArtists: "Mis artistas",
  manage: "gestionar →",
  noBestOf: "Todavía no hay datos de Best of. Ejecuta ",
  noBestOfAfter: ".",
  bestOfYear: "Lo mejor de {year}",
  yearLabel: "Año",
  categoriesLabel: "Categorías",
  numberOne: "Número 1",
  ratingsLabel: "Puntuaciones",
};

const de: T = {
  emptyList: "Noch leer — sei der Erste.",
  bannerTitle: "Listen",
  bannerIntro: "Fest: ",
  weeklyReleasesLink: "Freitagsneuerscheinungen",
  bannerConnected: " ({n} mit MusicBrainz verknüpft) und ",
  bestOfLink: "Best of des Jahres",
  bannerOutro: ". Darunter die Listen der Portal-Community.",
  titleTopAlbums: "Bestbewertete Alben",
  titleTopArtists: "Bestbewertete Künstler",
  titleMostLiked: "Meistgemochte Alben",
  titleMostFav: "Meiste Favoriten",
  titleMostCommentedAlbums: "Meistkommentierte Alben",
  titleMostCommentedArtists: "Meistkommentierte Künstler",
  commentsCount: "{n} Komm.",
  myAlbums: "Meine Alben",
  myArtists: "Meine Künstler",
  manage: "verwalten →",
  noBestOf: "Noch keine Best-of-Daten. Führe ",
  noBestOfAfter: " aus.",
  bestOfYear: "Best of {year}",
  yearLabel: "Jahr",
  categoriesLabel: "Kategorien",
  numberOne: "Nummer 1",
  ratingsLabel: "Wertungen",
};

export const lists: Record<Locale, T> = { pl, en, es, de };
