/**
 * Nagłówek, stopka i rzeczy wspólne dla całego portalu.
 *
 * Wzór dla wszystkich plików słownika: polski jest źródłem prawdy i z niego
 * bierzemy typ, więc brak klucza w innym języku wywala build, a nie stronę.
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  releases: "Premiery",
  concerts: "Koncerty",
  bestOf: "Best of",
  lists: "Podróże",
  chat: "W nieznane",
  logIn: "Zaloguj",
  logOut: "wyloguj",
  me: "Profil",
  search: "Szukaj",
  back: "Wstecz",
  share: "Skopiuj adres tej strony",
  shareCopied: "Adres skopiowany",
  shareFailed: "Nie udało się skopiować",
  playSpotify: "Graj w Spotify",
  openTidalApp: "Graj w Tidalu",
  spotifyWeb: "Spotify w przeglądarce",
  tidalWeb: "Tidal w przeglądarce",
  playMore: "Inne sposoby słuchania",
  playingOn: "Gra na: {urzadzenie}",
  playNoDevice: "Spotify nie jest nigdzie otwarte — włącz je na komputerze albo telefonie i kliknij jeszcze raz.",
  playNeedsConsent: "Połącz Spotify jeszcze raz w profilu — portal potrzebuje zgody na sterowanie odtwarzaniem.",
  playPremium: "Odtwarzanie z portalu działa tylko ze Spotify Premium.",
  playFailed: "Nie udało się puścić — otwieram płytę w Spotify.",
  tidalNotFound: "Nie znalazłam tej płyty w katalogu Tidala.",
  myTops: "Moje topy",
  topsIntro: "Twoje w jednym miejscu: najwyżej ocenione płyty, ulubione i to, czego słuchasz najczęściej. Widzisz to tylko Ty.",
  topsRated: "Najwyżej ocenione",
  topsLiked: "Ulubione płyty",
  topsArtists: "Ulubieni artyści",
  topsPlayedArtists: "Najczęściej grani",
  topsPlayedAlbums: "Najczęściej grane płyty",
  topsEmpty: "Jeszcze pusto. Oceniaj płyty, dawaj ★ zespołom i słuchaj stąd — topy złożą się same.",
  searchPlaceholder: "artysta, płyta, muzyk…",
  language: "Język",
  siteDescription: "Premiery, best of i podróż po płytach, artystach i muzykach. Metal, prog, jazz.",
  footer: "Dane: MusicBrainz · Wikipedia · Cover Art Archive. Oceny i komentarze należą do użytkowników portalu.",
};
type T = typeof pl;

const en: T = {
  releases: "New releases",
  concerts: "Concerts",
  bestOf: "Best of",
  lists: "Journeys",
  chat: "Into the unknown",
  logIn: "Sign in",
  logOut: "sign out",
  me: "Profile",
  search: "Search",
  back: "Back",
  share: "Copy this page’s link",
  shareCopied: "Link copied",
  shareFailed: "Could not copy",
  playSpotify: "Play on Spotify",
  openTidalApp: "Play in Tidal",
  spotifyWeb: "Spotify in the browser",
  tidalWeb: "Tidal in the browser",
  playMore: "Other ways to listen",
  playingOn: "Playing on: {urzadzenie}",
  playNoDevice: "Spotify isn’t open anywhere — start it on your computer or phone and click again.",
  playNeedsConsent: "Reconnect Spotify in your profile — the site needs permission to control playback.",
  playPremium: "Playing from the site only works with Spotify Premium.",
  playFailed: "Couldn’t start playback — opening the album in Spotify.",
  tidalNotFound: "I couldn’t find this album in the Tidal catalogue.",
  myTops: "My tops",
  topsIntro: "Yours in one place: top-rated albums, favourites and what you play most. Only you can see this.",
  topsRated: "Top rated",
  topsLiked: "Favourite albums",
  topsArtists: "Favourite artists",
  topsPlayedArtists: "Most played artists",
  topsPlayedAlbums: "Most played albums",
  topsEmpty: "Nothing yet. Rate albums, star bands and listen from here — your tops will build themselves.",
  searchPlaceholder: "artist, album, musician…",
  language: "Language",
  siteDescription: "New releases, best-of lists and a journey through albums, bands and musicians. Metal, prog, jazz.",
  footer: "Data: MusicBrainz · Wikipedia · Cover Art Archive. Ratings and comments belong to the people who wrote them.",
};

const es: T = {
  releases: "Novedades",
  concerts: "Conciertos",
  bestOf: "Lo mejor",
  lists: "Viajes",
  chat: "Hacia lo desconocido",
  logIn: "Iniciar sesión",
  logOut: "cerrar sesión",
  me: "Perfil",
  search: "Buscar",
  back: "Atrás",
  share: "Copiar el enlace de esta página",
  shareCopied: "Enlace copiado",
  shareFailed: "No se pudo copiar",
  playSpotify: "Reproducir en Spotify",
  openTidalApp: "Reproducir en Tidal",
  spotifyWeb: "Spotify en el navegador",
  tidalWeb: "Tidal en el navegador",
  playMore: "Otras formas de escuchar",
  playingOn: "Sonando en: {urzadzenie}",
  playNoDevice: "Spotify no está abierto en ningún dispositivo: ábrelo en el ordenador o el móvil y vuelve a pulsar.",
  playNeedsConsent: "Vuelve a conectar Spotify en tu perfil: el portal necesita permiso para controlar la reproducción.",
  playPremium: "Reproducir desde el portal solo funciona con Spotify Premium.",
  playFailed: "No se pudo reproducir: abro el disco en Spotify.",
  tidalNotFound: "No encontré este disco en el catálogo de Tidal.",
  myTops: "Mis tops",
  topsIntro: "Lo tuyo en un sitio: discos mejor valorados, favoritos y lo que más escuchas. Solo lo ves tú.",
  topsRated: "Mejor valorados",
  topsLiked: "Discos favoritos",
  topsArtists: "Artistas favoritos",
  topsPlayedArtists: "Más escuchados",
  topsPlayedAlbums: "Discos más escuchados",
  topsEmpty: "Aún vacío. Valora discos, marca bandas con ★ y escucha desde aquí: los tops se arman solos.",
  searchPlaceholder: "banda, disco, músico…",
  language: "Idioma",
  siteDescription: "Novedades, listas de lo mejor y un viaje por discos, bandas y músicos. Metal, prog, jazz.",
  footer: "Datos: MusicBrainz · Wikipedia · Cover Art Archive. Las valoraciones y los comentarios pertenecen a quienes los escriben.",
};

const de: T = {
  releases: "Neuerscheinungen",
  concerts: "Konzerte",
  bestOf: "Best of",
  lists: "Reisen",
  chat: "Ins Unbekannte",
  logIn: "Anmelden",
  logOut: "abmelden",
  me: "Profil",
  search: "Suchen",
  back: "Zurück",
  share: "Link dieser Seite kopieren",
  shareCopied: "Link kopiert",
  shareFailed: "Kopieren nicht möglich",
  playSpotify: "In Spotify abspielen",
  openTidalApp: "In Tidal abspielen",
  spotifyWeb: "Spotify im Browser",
  tidalWeb: "Tidal im Browser",
  playMore: "Andere Wege zum Hören",
  playingOn: "Läuft auf: {urzadzenie}",
  playNoDevice: "Spotify ist nirgends geöffnet — starte es auf dem Computer oder Handy und klicke noch einmal.",
  playNeedsConsent: "Verbinde Spotify im Profil neu — das Portal braucht die Erlaubnis, die Wiedergabe zu steuern.",
  playPremium: "Abspielen aus dem Portal geht nur mit Spotify Premium.",
  playFailed: "Abspielen hat nicht geklappt — ich öffne das Album in Spotify.",
  tidalNotFound: "Dieses Album habe ich im Tidal-Katalog nicht gefunden.",
  myTops: "Meine Tops",
  topsIntro: "Deins an einem Ort: bestbewertete Alben, Favoriten und was du am meisten hörst. Nur du siehst das.",
  topsRated: "Bestbewertet",
  topsLiked: "Lieblingsalben",
  topsArtists: "Lieblingskünstler",
  topsPlayedArtists: "Am meisten gehört",
  topsPlayedAlbums: "Am meisten gehörte Alben",
  topsEmpty: "Noch leer. Bewerte Alben, markiere Bands mit ★ und hör von hier aus — die Tops entstehen von selbst.",
  searchPlaceholder: "Band, Album, Musiker…",
  language: "Sprache",
  siteDescription: "Neuerscheinungen, Best-of-Listen und eine Reise durch Alben, Bands und Musiker. Metal, Prog, Jazz.",
  footer: "Daten: MusicBrainz · Wikipedia · Cover Art Archive. Bewertungen und Kommentare gehören denen, die sie geschrieben haben.",
};

export const nav: Record<Locale, T> = { pl, en, es, de };
