/**
 * Nagłówek, stopka i rzeczy wspólne dla całego portalu.
 *
 * Wzór dla wszystkich plików słownika: polski jest źródłem prawdy i z niego
 * bierzemy typ, więc brak klucza w innym języku wywala build, a nie stronę.
 */
import type { Locale } from "@/lib/i18n";

const pl = {
  releases: "Premiery",
  concerts: "Koncerty",
  bestOf: "Best of",
  lists: "Podróże",
  chat: "W nieznane",
  logIn: "Zaloguj",
  logOut: "wyloguj",
  me: "Profil",
  search: "Szukaj",
  back: "Wstecz",
  share: "Skopiuj adres tej strony",
  shareCopied: "Adres skopiowany",
  shareFailed: "Nie udało się skopiować",
  playSpotify: "Graj w Spotify",
  openTidalApp: "Otwórz w aplikacji Tidal",
  spotifyWeb: "Spotify w przeglądarce",
  tidalWeb: "Tidal w przeglądarce",
  playMore: "Inne sposoby słuchania",
  playingOn: "Gra na: {urzadzenie}",
  playNoDevice: "Spotify nie jest nigdzie otwarte — włącz je na komputerze albo telefonie i kliknij jeszcze raz.",
  playNeedsConsent: "Połącz Spotify jeszcze raz w profilu — portal potrzebuje zgody na sterowanie odtwarzaniem.",
  playPremium: "Odtwarzanie z portalu działa tylko ze Spotify Premium.",
  playFailed: "Nie udało się puścić — otwieram płytę w Spotify.",
  tidalNotFound: "Nie znalazłam tej płyty w katalogu Tidala.",
  searchPlaceholder: "artysta, płyta, muzyk…",
  language: "Język",
  siteDescription: "Premiery, best of i podróż po płytach, artystach i muzykach. Metal, prog, jazz.",
  footer: "Dane: MusicBrainz · Wikipedia · Cover Art Archive. Oceny i komentarze należą do użytkowników portalu.",
};
type T = typeof pl;

const en: T = {
  releases: "New releases",
  concerts: "Concerts",
  bestOf: "Best of",
  lists: "Journeys",
  chat: "Into the unknown",
  logIn: "Sign in",
  logOut: "sign out",
  me: "Profile",
  search: "Search",
  back: "Back",
  share: "Copy this page’s link",
  shareCopied: "Link copied",
  shareFailed: "Could not copy",
  playSpotify: "Play on Spotify",
  openTidalApp: "Open in the Tidal app",
  spotifyWeb: "Spotify in the browser",
  tidalWeb: "Tidal in the browser",
  playMore: "Other ways to listen",
  playingOn: "Playing on: {urzadzenie}",
  playNoDevice: "Spotify isn’t open anywhere — start it on your computer or phone and click again.",
  playNeedsConsent: "Reconnect Spotify in your profile — the site needs permission to control playback.",
  playPremium: "Playing from the site only works with Spotify Premium.",
  playFailed: "Couldn’t start playback — opening the album in Spotify.",
  tidalNotFound: "I couldn’t find this album in the Tidal catalogue.",
  searchPlaceholder: "artist, album, musician…",
  language: "Language",
  siteDescription: "New releases, best-of lists and a journey through albums, bands and musicians. Metal, prog, jazz.",
  footer: "Data: MusicBrainz · Wikipedia · Cover Art Archive. Ratings and comments belong to the people who wrote them.",
};

const es: T = {
  releases: "Novedades",
  concerts: "Conciertos",
  bestOf: "Lo mejor",
  lists: "Viajes",
  chat: "Hacia lo desconocido",
  logIn: "Iniciar sesión",
  logOut: "cerrar sesión",
  me: "Perfil",
  search: "Buscar",
  back: "Atrás",
  share: "Copiar el enlace de esta página",
  shareCopied: "Enlace copiado",
  shareFailed: "No se pudo copiar",
  playSpotify: "Reproducir en Spotify",
  openTidalApp: "Abrir en la app de Tidal",
  spotifyWeb: "Spotify en el navegador",
  tidalWeb: "Tidal en el navegador",
  playMore: "Otras formas de escuchar",
  playingOn: "Sonando en: {urzadzenie}",
  playNoDevice: "Spotify no está abierto en ningún dispositivo: ábrelo en el ordenador o el móvil y vuelve a pulsar.",
  playNeedsConsent: "Vuelve a conectar Spotify en tu perfil: el portal necesita permiso para controlar la reproducción.",
  playPremium: "Reproducir desde el portal solo funciona con Spotify Premium.",
  playFailed: "No se pudo reproducir: abro el disco en Spotify.",
  tidalNotFound: "No encontré este disco en el catálogo de Tidal.",
  searchPlaceholder: "banda, disco, músico…",
  language: "Idioma",
  siteDescription: "Novedades, listas de lo mejor y un viaje por discos, bandas y músicos. Metal, prog, jazz.",
  footer: "Datos: MusicBrainz · Wikipedia · Cover Art Archive. Las valoraciones y los comentarios pertenecen a quienes los escriben.",
};

const de: T = {
  releases: "Neuerscheinungen",
  concerts: "Konzerte",
  bestOf: "Best of",
  lists: "Reisen",
  chat: "Ins Unbekannte",
  logIn: "Anmelden",
  logOut: "abmelden",
  me: "Profil",
  search: "Suchen",
  back: "Zurück",
  share: "Link dieser Seite kopieren",
  shareCopied: "Link kopiert",
  shareFailed: "Kopieren nicht möglich",
  playSpotify: "In Spotify abspielen",
  openTidalApp: "In der Tidal-App öffnen",
  spotifyWeb: "Spotify im Browser",
  tidalWeb: "Tidal im Browser",
  playMore: "Andere Wege zum Hören",
  playingOn: "Läuft auf: {urzadzenie}",
  playNoDevice: "Spotify ist nirgends geöffnet — starte es auf dem Computer oder Handy und klicke noch einmal.",
  playNeedsConsent: "Verbinde Spotify im Profil neu — das Portal braucht die Erlaubnis, die Wiedergabe zu steuern.",
  playPremium: "Abspielen aus dem Portal geht nur mit Spotify Premium.",
  playFailed: "Abspielen hat nicht geklappt — ich öffne das Album in Spotify.",
  tidalNotFound: "Dieses Album habe ich im Tidal-Katalog nicht gefunden.",
  searchPlaceholder: "Band, Album, Musiker…",
  language: "Sprache",
  siteDescription: "Neuerscheinungen, Best-of-Listen und eine Reise durch Alben, Bands und Musiker. Metal, Prog, Jazz.",
  footer: "Daten: MusicBrainz · Wikipedia · Cover Art Archive. Bewertungen und Kommentare gehören denen, die sie geschrieben haben.",
};

export const nav: Record<Locale, T> = { pl, en, es, de };
