/** Napisy ekranu: profile. Polski jest źródłem prawdy — z niego bierzemy typ. */
import type { Locale } from "@/lib/i18n";

const pl = {
  dislikedTitle: "Nie moja bajka",
  dislikedExplain: "Nie chodzi o to, że to złe — po prostu nie Twój klimat. Portal nie będzie Ci tego podsuwał.",
  undislike: "cofnij",
  statsTitle: "Statystyki portalu",
  statsExplain: "Widzisz to, bo Twoje konto jest na liście administratorów portalu.",
  statsUsers: { one: "{n} zarejestrowana osoba", few: "{n} zarejestrowane osoby", many: "{n} zarejestrowanych osób" } as { one: string; few?: string; many: string },
  spotifyNote: "Po połączeniu portal pokaże, czego właśnie słuchasz, i będzie mógł zapisać podróż jako prywatną playlistę. Prosimy tylko o te dwie rzeczy — sterowania odtwarzaniem ani Twojej biblioteki nie ruszamy.",
  spotifyConnected: "Konto połączone.",
  welcomeEyebrow: "Witaj w portalu",
  welcomeTitle: "Zacznijmy od tego, czego słuchasz",
  welcomeBody: "Wybierz poniżej kategorie, które lubisz — klikasz w kafelek, żeby dodać. Od nich zależy, czym portal Cię wita, w jakiej kolejności układa premiery i o czyich zmianach w składach Ci mówi. Zawsze możesz to zmienić na tej stronie.",
  chooseLater: "wybiorę później",
  profileLabel: "Profil",

  areasTitle: "Koncerty — moje obszary",
  areasIntro1: "Dwie osobne listy, bo to dwa różne apetyty: po ulubiony zespół jedzie się przez pół kraju, a „coś w moich gatunkach” ogląda się u siebie. Zostaw miasto puste, żeby śledzić cały kraj. Na tej podstawie buduję",
  areasIntroLink: "listę koncertów",
  areasIntro2: "na najbliższe trzy miesiące.",
  genresScopeTitle: "Dla moich gatunków",
  genresScopeHint: "np. Kraków, Warszawa",
  favoritesScopeTitle: "Dla ulubionych zespołów",
  favoritesScopeHint: "np. cała Polska",
  wholeCountry: "cały kraj: {country}",
  removeAreaTitle: "Usuń obszar",
  noAreaChosen: "Nic jeszcze nie wybrałeś ({hint}).",
  cityLabel: "Miasto",
  cityPlaceholder: "puste = cały kraj",
  countryLabel: "Kraj",
  addButton: "Dodaj",
  areaFootnote: "Kraj podaje się dwuliterowym kodem: PL, DE, CZ, GB. Miasto wpisz tak, jak nazywa się lokalnie (Warszawa, Kraków, Berlin).",

  stylesTitle: "Style muzyczne",
  stylesIntro: "Wybierz główne kategorie, których słuchasz — klikasz, żeby dodać (waga 3), potem ustawiasz wagę 1–5. Kategoria z najwyższą wagą jest Twoim stylem wiodącym: pod nią dobieramy oprawę graficzną portalu, a kategorie z wagą ≥3 filtrują premiery.",
  yourStyles: "Twoje style",
  weight1: "od czasu do czasu",
  weight2: "lubię",
  weight3: "często",
  weight4: "bardzo",
  weight5: "to moje serce",
  removeWeight: "usuń",
  tileAddHint: "kliknij, żeby dodać",
  tileOnHint: "w profilu · waga {w}",
  customGenresTitle: "Z wcześniejszych ustawień (podgatunki)",
  removeCustomGenreTitle: "kliknij, żeby usunąć",
  customGenresFootnote: "Wybór zawęziliśmy do głównych kategorii — dla podgatunków nie da się co tydzień budować osobnych list. Podgatunki dalej służą do klasyfikowania płyt.",

  likedAlbumsTitle: "Płyty, które lubię",
  addAlbum: "+ dodaj płytę",
  removeAlbum: "usuń",
  noLikedAlbums: "Jeszcze nic. Na stronie płyty kliknij „Lubię tę płytę” albo dodaj z wyszukiwarki.",

  favoriteArtistsTitle: "Ulubieni artyści",
  noFavoriteArtists: "Na stronie artysty kliknij „Do ulubionych”.",

  myAlbumRatings: "Moje oceny płyt",
  myArtistRatings: "Moje oceny artystów",

  languageTitle: "Język portalu",
  languageExplain: "Wybór zapisuje się w Twoim profilu i idzie za Tobą na inne urządzenia.",
};
type T = typeof pl;

const en: T = {
  dislikedTitle: "Not my thing",
  dislikedExplain: "Not a verdict that it\u2019s bad — simply not your kind of thing. The portal will stop pushing it your way.",
  undislike: "undo",
  statsTitle: "Portal statistics",
  statsExplain: "You see this because your account is on the portal's admin list.",
  statsUsers: { one: "{n} registered person", many: "{n} registered people" },
  spotifyNote: "Once connected, the portal can show what you\u2019re listening to and save a journey as a private playlist. We ask for those two things only — no playback control, no library access.",
  spotifyConnected: "Account connected.",
  welcomeEyebrow: "Welcome to the portal",
  welcomeTitle: "Let's start with what you listen to",
  welcomeBody: "Pick the categories you're into below — click a tile to add it. They decide how the portal greets you, in what order it orders new releases, and whose line-up changes it tells you about. You can always change this here.",
  chooseLater: "I'll choose later",
  profileLabel: "Profile",

  areasTitle: "Concerts — my areas",
  areasIntro1: "Two separate lists, because these are two different appetites: you'll cross half the country for a favourite band, but „something in my genres” you want close to home. Leave the city blank to follow the whole country. This is what I use to build your",
  areasIntroLink: "concert list",
  areasIntro2: "for the next three months.",
  genresScopeTitle: "For my genres",
  genresScopeHint: "e.g. Kraków, Warsaw",
  favoritesScopeTitle: "For favourite bands",
  favoritesScopeHint: "e.g. all of Poland",
  wholeCountry: "whole country: {country}",
  removeAreaTitle: "Remove area",
  noAreaChosen: "Nothing chosen yet ({hint}).",
  cityLabel: "City",
  cityPlaceholder: "blank = whole country",
  countryLabel: "Country",
  addButton: "Add",
  areaFootnote: "Give the country as a two-letter code: PL, DE, CZ, GB. Type the city the way it's called locally (Warszawa, Kraków, Berlin).",

  stylesTitle: "Musical styles",
  stylesIntro: "Pick the main categories you listen to — click to add (weight 3), then set a weight from 1 to 5. The category with the highest weight is your leading style: it decides the portal's look, and categories at weight ≥3 filter your new releases.",
  yourStyles: "Your styles",
  weight1: "now and then",
  weight2: "I like it",
  weight3: "often",
  weight4: "a lot",
  weight5: "it's my heart",
  removeWeight: "remove",
  tileAddHint: "click to add",
  tileOnHint: "in your profile · weight {w}",
  customGenresTitle: "From earlier settings (subgenres)",
  removeCustomGenreTitle: "click to remove",
  customGenresFootnote: "We narrowed the choice to the main categories — you can't build separate weekly lists for every subgenre. Subgenres still classify albums, though.",

  likedAlbumsTitle: "Albums I like",
  addAlbum: "+ add an album",
  removeAlbum: "remove",
  noLikedAlbums: "Nothing yet. Click „I like this album” on an album page, or add one from the search box.",

  favoriteArtistsTitle: "Favourite artists",
  noFavoriteArtists: "Click „Add to favourites” on an artist page.",

  myAlbumRatings: "My album ratings",
  myArtistRatings: "My artist ratings",

  languageTitle: "Portal language",
  languageExplain: "Your choice is saved in your profile and follows you to other devices.",
};

const es: T = {
  dislikedTitle: "No es lo mío",
  dislikedExplain: "No es que sea malo — sencillamente no es lo tuyo. El portal dejará de proponértelo.",
  undislike: "deshacer",
  statsTitle: "Estadísticas del portal",
  statsExplain: "Ves esto porque tu cuenta está en la lista de administradores del portal.",
  statsUsers: { one: "{n} persona registrada", many: "{n} personas registradas" },
  spotifyNote: "Una vez conectado, el portal puede mostrar qué estás escuchando y guardar un viaje como lista privada. Solo pedimos eso: ni control de reproducción ni acceso a tu biblioteca.",
  spotifyConnected: "Cuenta conectada.",
  welcomeEyebrow: "Bienvenido al portal",
  welcomeTitle: "Empecemos por lo que escuchas",
  welcomeBody: "Elige abajo las categorías que te gustan — haz clic en una para añadirla. De ellas depende cómo te recibe el portal, en qué orden ordena las novedades y de qué cambios de formación te habla. Siempre puedes cambiarlo en esta página.",
  chooseLater: "lo elegiré más tarde",
  profileLabel: "Perfil",

  areasTitle: "Conciertos — mis zonas",
  areasIntro1: "Dos listas separadas, porque son dos apetitos distintos: por una banda favorita cruzas medio país, pero «algo en mis géneros» lo quieres cerca de casa. Deja la ciudad en blanco para seguir todo el país. Con esto construyo tu",
  areasIntroLink: "lista de conciertos",
  areasIntro2: "para los próximos tres meses.",
  genresScopeTitle: "Para mis géneros",
  genresScopeHint: "p. ej. Cracovia, Varsovia",
  favoritesScopeTitle: "Para bandas favoritas",
  favoritesScopeHint: "p. ej. toda Polonia",
  wholeCountry: "todo el país: {country}",
  removeAreaTitle: "Eliminar zona",
  noAreaChosen: "Aún no has elegido nada ({hint}).",
  cityLabel: "Ciudad",
  cityPlaceholder: "en blanco = todo el país",
  countryLabel: "País",
  addButton: "Añadir",
  areaFootnote: "El país se indica con un código de dos letras: PL, DE, CZ, GB. Escribe la ciudad como se llama localmente (Warszawa, Kraków, Berlin).",

  stylesTitle: "Estilos musicales",
  stylesIntro: "Elige las categorías principales que escuchas — haz clic para añadir (peso 3) y luego ajusta el peso de 1 a 5. La categoría con el peso más alto es tu estilo principal: define el aspecto del portal, y las categorías con peso ≥3 filtran las novedades.",
  yourStyles: "Tus estilos",
  weight1: "de vez en cuando",
  weight2: "me gusta",
  weight3: "a menudo",
  weight4: "mucho",
  weight5: "es mi debilidad",
  removeWeight: "quitar",
  tileAddHint: "haz clic para añadir",
  tileOnHint: "en tu perfil · peso {w}",
  customGenresTitle: "De ajustes anteriores (subgéneros)",
  removeCustomGenreTitle: "haz clic para quitar",
  customGenresFootnote: "Hemos limitado la elección a las categorías principales — no se puede construir cada semana listas separadas para cada subgénero. Los subgéneros siguen sirviendo para clasificar discos.",

  likedAlbumsTitle: "Discos que me gustan",
  addAlbum: "+ añadir un disco",
  removeAlbum: "quitar",
  noLikedAlbums: "Todavía nada. En la página de un disco haz clic en «Me gusta este disco», o añade uno desde el buscador.",

  favoriteArtistsTitle: "Artistas favoritos",
  noFavoriteArtists: "En la página de un artista haz clic en «Añadir a favoritos».",

  myAlbumRatings: "Mis valoraciones de discos",
  myArtistRatings: "Mis valoraciones de artistas",

  languageTitle: "Idioma del portal",
  languageExplain: "Tu elección se guarda en tu perfil y te acompaña a otros dispositivos.",
};

const de: T = {
  dislikedTitle: "Nicht mein Ding",
  dislikedExplain: "Kein Urteil über die Qualität — es ist einfach nicht deins. Das Portal schlägt es dir nicht mehr vor.",
  undislike: "rückgängig",
  statsTitle: "Portal-Statistik",
  statsExplain: "Du siehst das, weil dein Konto auf der Admin-Liste des Portals steht.",
  statsUsers: { one: "{n} registrierte Person", many: "{n} registrierte Personen" },
  spotifyNote: "Nach dem Verbinden zeigt das Portal, was du gerade hörst, und kann eine Reise als private Playlist speichern. Mehr fragen wir nicht ab — keine Wiedergabesteuerung, keine Bibliothek.",
  spotifyConnected: "Konto verbunden.",
  welcomeEyebrow: "Willkommen im Portal",
  welcomeTitle: "Fangen wir damit an, was du hörst",
  welcomeBody: "Wähle unten die Kategorien, die dir gefallen — klick auf eine Kachel, um sie hinzuzufügen. Danach richtet sich, wie das Portal dich begrüßt, in welcher Reihenfolge es Neuerscheinungen anordnet und über wessen Besetzungswechsel es dich informiert. Du kannst das hier jederzeit ändern.",
  chooseLater: "wähle ich später",
  profileLabel: "Profil",

  areasTitle: "Konzerte — meine Regionen",
  areasIntro1: "Zwei getrennte Listen, weil das zwei verschiedene Bedürfnisse sind: für eine Lieblingsband fährt man durchs halbe Land, aber „etwas in meinen Genres” will man in der Nähe. Lass die Stadt leer, um das ganze Land zu verfolgen. Darauf baue ich deine",
  areasIntroLink: "Konzertliste",
  areasIntro2: "für die nächsten drei Monate.",
  genresScopeTitle: "Für meine Genres",
  genresScopeHint: "z. B. Krakau, Warschau",
  favoritesScopeTitle: "Für Lieblingsbands",
  favoritesScopeHint: "z. B. ganz Polen",
  wholeCountry: "ganzes Land: {country}",
  removeAreaTitle: "Region entfernen",
  noAreaChosen: "Noch nichts ausgewählt ({hint}).",
  cityLabel: "Stadt",
  cityPlaceholder: "leer = ganzes Land",
  countryLabel: "Land",
  addButton: "Hinzufügen",
  areaFootnote: "Das Land gibst du als zweistelligen Code an: PL, DE, CZ, GB. Die Stadt so, wie sie vor Ort heißt (Warszawa, Kraków, Berlin).",

  stylesTitle: "Musikstile",
  stylesIntro: "Wähle die Hauptkategorien, die du hörst — klick, um hinzuzufügen (Gewicht 3), dann stellst du ein Gewicht von 1 bis 5 ein. Die Kategorie mit dem höchsten Gewicht ist dein Leitstil: danach richtet sich die Optik des Portals, und Kategorien mit Gewicht ≥3 filtern die Neuerscheinungen.",
  yourStyles: "Deine Stile",
  weight1: "hin und wieder",
  weight2: "mag ich",
  weight3: "oft",
  weight4: "sehr",
  weight5: "das ist mein Herzstück",
  removeWeight: "entfernen",
  tileAddHint: "klicken zum Hinzufügen",
  tileOnHint: "im Profil · Gewicht {w}",
  customGenresTitle: "Aus früheren Einstellungen (Subgenres)",
  removeCustomGenreTitle: "klicken zum Entfernen",
  customGenresFootnote: "Wir haben die Auswahl auf die Hauptkategorien beschränkt — für Subgenres lassen sich nicht jede Woche eigene Listen erstellen. Subgenres dienen weiterhin dazu, Alben zu klassifizieren.",

  likedAlbumsTitle: "Alben, die mir gefallen",
  addAlbum: "+ Album hinzufügen",
  removeAlbum: "entfernen",
  noLikedAlbums: "Noch nichts. Klick auf einer Albumseite auf „Gefällt mir” oder füge eins über die Suche hinzu.",

  favoriteArtistsTitle: "Lieblingskünstler",
  noFavoriteArtists: "Klick auf einer Künstlerseite auf „Zu Favoriten”.",

  myAlbumRatings: "Meine Album-Bewertungen",
  myArtistRatings: "Meine Künstler-Bewertungen",

  languageTitle: "Portalsprache",
  languageExplain: "Deine Wahl wird in deinem Profil gespeichert und begleitet dich auf andere Geräte.",
};

export const profile: Record<Locale, T> = { pl, en, es, de };
