/** Napisy ekranu: releases. Polski jest źródłem prawdy — z niego bierzemy typ. */
import type { Locale } from "@/lib/i18n";

const pl = {
  eyebrow: "Premiery płytowe co piątek",
  journeyFromReleases: "Utwórz podróż po premierach",
  journeyFromReleasesNote: "Dokładnie to, co widzisz powyżej — ten tydzień i ten filtr — jako jedna podróż.",
  fridayPrefix: "Piątek",
  leadGenre: "Twój styl wiodący:",
  setStyles: "Ustaw swoje style",
  setStylesRest: ", żeby portal dobrał oprawę i filtry pod Ciebie.",
  genresLabel: "Gatunki",
  viewLabel: "Widok",
  starOnly: "Tylko ★",
  showFlagged: "Pokaż reedycje / EP / live",
  footnote: "Lista powstaje co piątek z zestawienia „Pure New Shit”. Kliknięcie w tytuł otwiera stronę płyty ze składem — stamtąd ruszasz w podróż.",
  noSectionsBefore: "Brak zaimportowanych premier. Uruchom ",
  noSectionsAfter: ".",
  noMatch: "Nic nie pasuje do filtrów.",
  weekPick: "Płyta tygodnia",
  reviews: "Recenzje",
  travelCta: "skład i podróż →",
  flagEp: "EP",
  flagComp: "kompilacja",
  flagReissue: "reedycja",
  flagLive: "live",
  flagInstr: "instrumental",
};
type T = typeof pl;

const en: T = {
  eyebrow: "New releases, every Friday",
  journeyFromReleases: "Build a journey from this week",
  journeyFromReleasesNote: "Exactly what you see above — this week, this filter — as one journey.",
  fridayPrefix: "Friday",
  leadGenre: "Your leading style:",
  setStyles: "Set your styles",
  setStylesRest: ", and the portal will pick the artwork and filters for you.",
  genresLabel: "Genres",
  viewLabel: "View",
  starOnly: "★ only",
  showFlagged: "Show reissues / EPs / live",
  footnote: "The list is built every Friday from the “Pure New Shit” roundup. Click a title to open the album page with its lineup — that's where your journey starts.",
  noSectionsBefore: "No releases imported yet. Run ",
  noSectionsAfter: ".",
  noMatch: "Nothing matches these filters.",
  weekPick: "Release of the week",
  reviews: "Reviews",
  travelCta: "lineup and journey →",
  flagEp: "EP",
  flagComp: "compilation",
  flagReissue: "reissue",
  flagLive: "live",
  flagInstr: "instrumental",
};

const es: T = {
  eyebrow: "Novedades cada viernes",
  journeyFromReleases: "Crear un viaje con las novedades",
  journeyFromReleasesNote: "Exactamente lo que ves arriba — esta semana, este filtro — como un viaje.",
  fridayPrefix: "Viernes",
  leadGenre: "Tu estilo destacado:",
  setStyles: "Elige tus estilos",
  setStylesRest: " y el portal ajustará por ti la imagen y los filtros.",
  genresLabel: "Géneros",
  viewLabel: "Vista",
  starOnly: "Solo ★",
  showFlagged: "Mostrar reediciones / EP / directos",
  footnote: "La lista se genera cada viernes a partir del resumen «Pure New Shit». Haz clic en un título para abrir la página del disco con su formación — ahí empieza tu viaje.",
  noSectionsBefore: "Todavía no hay novedades importadas. Ejecuta ",
  noSectionsAfter: ".",
  noMatch: "Nada coincide con estos filtros.",
  weekPick: "Disco de la semana",
  reviews: "Reseñas",
  travelCta: "formación y viaje →",
  flagEp: "EP",
  flagComp: "recopilatorio",
  flagReissue: "reedición",
  flagLive: "directo",
  flagInstr: "instrumental",
};

const de: T = {
  eyebrow: "Neuerscheinungen, jeden Freitag",
  journeyFromReleases: "Reise aus den Neuheiten bauen",
  journeyFromReleasesNote: "Genau das, was du oben siehst — diese Woche, dieser Filter — als eine Reise.",
  fridayPrefix: "Freitag",
  leadGenre: "Dein Leitstil:",
  setStyles: "Leg deine Stile fest",
  setStylesRest: ", dann wählt das Portal Bildsprache und Filter für dich.",
  genresLabel: "Genres",
  viewLabel: "Ansicht",
  starOnly: "Nur ★",
  showFlagged: "Wiederveröffentlichungen / EPs / Live zeigen",
  footnote: "Die Liste entsteht jeden Freitag aus der Übersicht „Pure New Shit“. Klick auf einen Titel, um die Albumseite mit der Besetzung zu öffnen — dort beginnt deine Reise.",
  noSectionsBefore: "Noch keine Neuerscheinungen importiert. Führe ",
  noSectionsAfter: " aus.",
  noMatch: "Nichts passt zu diesen Filtern.",
  weekPick: "Album der Woche",
  reviews: "Rezensionen",
  travelCta: "Besetzung und Reise →",
  flagEp: "EP",
  flagComp: "Kompilation",
  flagReissue: "Wiederveröffentlichung",
  flagLive: "Live",
  flagInstr: "instrumental",
};

export const releases: Record<Locale, T> = { pl, en, es, de };
